<?php
/**
 * Webkul Software
 *
 * @category Webkul
 * @package Webkul_MpWalletSystem
 * @author Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license https://store.webkul.com/license.html
 */

use \Webkul\MpWalletSystem\Model\Wallettransaction;

$helper = $block->getWalletHelper();
if ($helper->getWalletenabled()) {
    $transactionData = $block->getTransactionData();
    $customer = $helper->getCustomerByCustomerId($transactionData->getCustomerId());
        
    $prefix = $helper->getTransactionPrefix($transactionData->getSenderType(), $transactionData->getAction()); ?>
        <div class="wk_ws_main">
            <div class='wk_ws_body'>
                <table class="wallet-transaction-view data-grid">
                    <tbody>
                        <tr>
                            <th><?=$block->escapeHtml(__("Customer Name"))?></th>
                            <td>
                            <?= $block->escapeHtml($customer->getFirstname()).
                                " ".
                                $block->escapeHtml($customer->getLastname());?></td>
                        </tr>
                        <tr>
                            <th><?=$block->escapeHtml(__("Email Address"))?></th>
                            <td><?=$block->escapeHtml($customer->getEmail())?></td>
                        </tr>
                         <tr>
                            <th><?=$block->escapeHtml(__("Amount"))?></th>
                            <td><?=/*@noEscape*/$block->getTransactionAmount($transactionData)?></td>
                        </tr>
                        <tr>
                            <th><?=$block->escapeHtml(__("Action"))?></th>
                            <td><?=$block->escapeHtml($transactionData->getAction())?></td>
                        </tr>
                        <?php
                        if ($transactionData->getOrderId()) {
                             $order = $block->getOrder()->load($transactionData->getOrderId());
                             $incrementid = $order->getIncrementId();
                        }
                        if ($transactionData->getSenderType()==Wallettransaction::ORDER_PLACE_TYPE) {
                            if ($transactionData->getAction()==Wallettransaction::WALLET_ACTION_TYPE_CREDIT) {?>
                                    <tr>
                                        <th><?=$block->escapeHtml(__("Type"))?></th>
                                        <td><?=$block->escapeHtml(__($prefix))?></td>
                                    </tr>
                                <?php } else { ?>
                                <tr>
                                    <th><?=$block->escapeHtml(__("Type"))?></th>
                                    <td><?=$block->escapeHtml(__($prefix))?></td>
                                </tr>
                            <?php } ?>
                            <tr>
                                <th><?=$block->escapeHtml(__("Reference"))?></th>
                                <td><a href="
                                <?=$block->escapeUrl($block->getUrl(
                                    'sales/order/view/',
                                    ['order_id'=>$transactionData->getOrderId()]
                                ));?>"><?=$block->escapeHtml("#".$incrementid)?></a></td>
                            </tr>
                        <?php } elseif ($transactionData->getSenderType()==Wallettransaction::CASH_BACK_TYPE) {
                            if ($transactionData->getAction() == Wallettransaction::WALLET_ACTION_TYPE_CREDIT) { ?>
                                <tr>
                                    <th><?=$block->escapeHtml(__("Type"))?></th>
                                    <td><?=$block->escapeHtml(__($prefix))?></td>
                                </tr>
                                <tr>
                                    <th><?=$block->escapeHtml(__("Reference"))?></th>
                                    <td><a href="
                                    <?=$block->escapeUrl($block->getUrl(
                                        'sales/order/view/',
                                        ['order_id'=>$transactionData->getOrderId()]
                                    ));?>"><?=$block->escapeHtml("#".$incrementid)?></a></td>
                                </tr>
                            <?php }
                        } elseif ($transactionData->getSenderType()==Wallettransaction::REFUND_TYPE) {
                            if ($transactionData->getAction()== Wallettransaction::WALLET_ACTION_TYPE_CREDIT) { ?>
                                <tr>
                                    <th><?=$block->escapeHtml(__("Type"))?></th>
                                    <td><?=$block->escapeHtml(__($prefix))?></td>
                                </tr>
                        <?php } else {?>
                            <tr>
                                <th><?=$block->escapeHtml(__("Type"))?></th>
                                <td><?=$block->escapeHtml(__($prefix))?></td>
                            </tr>
                        <?php }?>
                            <tr>
                                <th><?=$block->escapeHtml(__("Reference"))?></th>
                                <td><a href="
                                <?=$block->escapeUrl($block->getUrl(
                                    'sales/order/view/',
                                    ['order_id'=>$transactionData->getOrderId()]
                                ));?>"><?=$block->escapeHtml("#".$incrementid)?></a></td>
                            </tr>
                        <?php } elseif ($transactionData->getSenderType()== Wallettransaction::ADMIN_TRANSFER_TYPE) {
                            if ($transactionData->getAction()== Wallettransaction::WALLET_ACTION_TYPE_CREDIT) { ?>
                                <tr>
                                    <th><?=$block->escapeHtml(__("Type"))?></th>
                                    <td><?=$block->escapeHtml(__($prefix))?></td>
                                </tr>
                        <?php } else {?>
                            <tr>
                                <th><?=$block->escapeHtml(__("Type"))?></th>
                                <td><?=$block->escapeHtml(__($prefix))?></td>
                            </tr>
                        <?php }
                        } elseif ($transactionData->getSenderType()== Wallettransaction::CUSTOMER_TRANSFER_TYPE) {
                            if ($transactionData->getAction()== Wallettransaction::WALLET_ACTION_TYPE_CREDIT) {
                                $senderData = $block->getCustomerDataById($transactionData->getSenderId());
                                ?>
                            <tr>
                                <th><?=$block->escapeHtml(__("Type"))?></th>
                                <td><?=$block->escapeHtml(__($prefix))?></td>
                            </tr>
                            <tr>
                                <th><?=$block->escapeHtml(__("Sender"))?></th>
                                <td>
                                <?=$block->escapeHtml(__(
                                    $senderData->getFirstname().
                                    " ".
                                    $senderData->getLastname()
                                ))?></td>
                            </tr>
                        <?php } else {
                                $recieverData = $block->getCustomerDataById($transactionData->getSenderId());
                                ?>
                            <tr>
                                <th><?=$block->escapeHtml(__("Type"))?></th>
                                <td><?=$block->escapeHtml(__($prefix))?></td>
                            </tr>
                                <?php
                                if ($recieverData->getEntityId()) { ?>
                                    <tr>
                                        <th><?=$block->escapeHtml(__("Receiver"))?></th>
                                        <td>
                                        <?=$block->escapeHtml(__(
                                            $recieverData->getFirstname().
                                            " ".
                                            $recieverData->getLastname()
                                        ))?></td>
                                    </tr>
                                <?php } else { ?>
                                    <tr>
                                        <th><?=$block->escapeHtml(__("Receiver"))?></th>
                                        <td><?=$block->escapeHtml(__("Reciever not exists"))?></td>
                                    </tr>
                                <?php }
                                ?>
                        <?php }
                        } elseif ($transactionData->getSenderType()== Wallettransaction::CUSTOMER_TRANSFER_BANK_TYPE) {
                            if ($transactionData->getAction()== Wallettransaction::WALLET_ACTION_TYPE_DEBIT) { ?>
                                <tr>
                                    <th><?=$block->escapeHtml(__("Bank Details"))?></th>
                                    <td><?=/*@noEscape*/ nl2br($transactionData->getBankDetails())?></td>
                                </tr>
                        <?php }
                        } ?>
                        <tr>
                            <th><?=$block->escapeHtml(__("Transaction At"))?></th>
                            <?php $date = $transactionData->getTransactionAt();?>
                            <td><?=$block->escapeHtml($date)?></td>
                        </tr>
                        <tr>
                            <th><?=$block->escapeHtml(__("Transaction Note"))?></th>
                            <td><?=$block->escapeHtml($transactionData->getTransactionNote())?></td>
                        </tr>
                        <tr>
                            <th><?=$block->escapeHtml(__("Transaction Status"))?></th>
                            <td>
                               <?php if ($transactionData->getStatus()==Wallettransaction::WALLET_TRANS_STATE_PENDING) {
                                    echo $block->escapeHtml(__('Pending'));
                               }
                               if ($transactionData->getStatus()==Wallettransaction::WALLET_TRANS_STATE_CANCEL) {
                                   echo $block->escapeHtml(__('Cancelled'));
                               }
                               if ($transactionData->getStatus()==Wallettransaction::WALLET_TRANS_STATE_APPROVE) {
                                   echo $block->escapeHtml(__('Approved'));
                               }
                                ?>
                            </td>
                        </tr>
                        <?php if ($transactionData->getSenderType()==Wallettransaction::CUSTOMER_TRANSFER_BANK_TYPE &&
                         $transactionData->getStatus() ==Wallettransaction::WALLET_TRANS_STATE_PENDING) { ?>
                            <tr>
                                <th><?=$block->escapeHtml(__("Update status if amount is transferred"))?></th>
                                <td>
                                    <a href="
                                    <?=$block->escapeUrl($block->getUrl(
                                        'mpwalletsystem/wallet/banktransfer',
                                        [
                                            'entity_id'=>$transactionData->getEntityId()
                                        ]
                                    ))?>" onclick="return confirm('Are you sure you want to update it?');">
                                        <button><?=$block->escapeHtml(__("Approve"))?></button>
                                    </a>
                                    <a href="
                                    <?=$block->escapeUrl($block->getUrl(
                                        'mpwalletsystem/wallet/disapprove',
                                        [
                                            'entity_id'=>$transactionData->getEntityId()
                                        ]
                                    ))?>" onclick="return confirm('Are you sure you want to disapprove it?');">
                                        <button><?=$block->escapeHtml(__("Cancel"))?></button>
                                    </a>
                                </td>
                            </tr>
                        <?php }?>
                    </tbody>
                </table>
            </div>
        </div>
<?php }?>
