<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_RegionUpload
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
$countryList = $block->getCountryList();
$localeList = $block->getLocale();
// print_r($localeList); die;
?>
<form id="wk_region_add_form" data-mage-init='{"validation": {}}' method="GET" class="admin__scope-old edit-form" 
    action="<?= $escaper->escapeUrl($block->getUrl(
        'regionupload/add/save',
        ['_secure' => $block->getIsSecure()]
    ))?>">
    <div class="wk_main">
        <fieldset class="admin__fieldset" id="wk_upload">
            <div class="field admin__field _required">
                <label class="admin__field-label">
                    <?= $escaper->escapeHtml(__('Country')) ?>:
                </label>
                <div class="admin__field-control">
                    <select 
                        class="required-entry _required admin__control-select" 
                        name="wk_country_id" 
                        id="wk_country_id" 
                        aria-required="true"
                    >
                        <?php
                        foreach ($countryList as $pair) {
                            ?>
                            <option value="<?= $escaper->escapeHtml($pair['value']);
                            ?>"
                                >
                                <?= $escaper->escapeHtml($pair['label']);
                                ?>
                                </option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
                
            </div>
            
            <div class="admin__field _required" data-validate="{required:true}">
                <label class="admin__field-label required">
                    <?= $escaper->escapeHtml(__('Region Code')) ?>:
                </label>
                <div class="admin__field-control" >
                        <input type="text" id="wk_region_code" 
                        class="required-entry validate-no-html-tags admin__control-text" 
                        data-validate="{required:true}" placeholder="AF-BGL" name="wk_region_code" />
                </div>
            </div>
            <div class="field admin__field _required">
                <label class="admin__field-label">
                    <?= $escaper->escapeHtml(__('Default Name')) ?>:
                </label>
                <div class="admin__field-control _required">
                        <input type="text" id="wk_region_name" 
                        class=" required-entry admin__control-text" placeholder="Baghlan" name="wk_region_name" />
                </div>
               
            </div>
            <div class="field admin__field _required">
                <label class="admin__field-label">
                    <?= $escaper->escapeHtml(__('Region Name for Locale')) ?>:
                </label>
                <div class="admin__field-control _required">
                    <table class="admin__dynamic-rows admin__control-table locale-regionname">
                        <thead>
                            <tr>
                                <th data-repeat-index="0" class="_empty">
                                    <span>Locale</span>
                                </th>
                                <th class="_empty">
                                    <span>Region Name</span>
                                </th>
                                <th data-repeat-index="4" >
                                    <span></span>
                                </th>
                            </tr>
                        </thead>
                        <tbody class="body-regionname">
                            
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="3">
                                    <button type="button" id="add-btn">
                                        <span>Add</span>
                                    </button>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </fieldset>
    </div>
</form>

<form id="wk_regionupload_popup" method="POST" data-mage-init='{"validation": {}}'
class="admin__scope-old edit-form" enctype="multipart/form-data"
    action="<?= $escaper->escapeUrl($block->getUrl(
        'regionupload/csv/upload',
        ['_secure' => $block->getIsSecure()]
    ))?>" style="display:none">
        <fieldset class="admin__fieldset" id="wk_upload">
            <input type="hidden" name="form_key" value= "<?= $escaper->escapeHtml($block->getFormKey()) ?>"/>
        <div class="field admin__field required">
            <label class="admin__field-label">
                <?= $escaper->escapeHtml(__('Country')) ?>:
            </label>
            <div class="admin__field-control">
                <select  
                    class="required-entry _required admin__control-select" 
                    name="wk_country_id" 
                    id="wk_country_id" 
                    aria-required="true"
                >
                    <?php foreach ($countryList as $pair) { ?>
                        <option value="<?= $escaper->escapeHtml($pair['value']);
                        ?>"><?= $escaper->escapeHtml($pair['label']);?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="field admin__field _required">
            <label class="admin__field-label">
                <?= $escaper->escapeHtml(__('Upload CSV File')) ?>:
            </label>
            <div class="admin__field-control">
                    <input type="file" class="required-entry admin__control-text" name="wk_region_upload" />
                    <a href="<?= $escaper->escapeUrl($block->getSampleCsv()) ?>" 
                    name="sample_file"><?= $escaper->escapeHtml(__("Download Sample File")) ?></a>
            </div>
        </div>
    </fieldset>
</form>

<script id="row-template" type="text/x-magento-template">
    <tr class="data-row" data-repeat-index="<%- data.id %>" >
        <td>
            <div class="admin__field" data-index="website_id">  
                <div class="admin__field-control">
                    <select class="admin__control-select" name="regionname[<%- data.id %>][locale]">
                        <?php foreach ($localeList as $pair) { ?>
                            <option value="<?= $escaper->escapeHtml($pair['value']); ?>">
                                <?= $escaper->escapeHtml($pair['label']);?>
                            </option>
                        <?php } ?>
                    </select>
                </div>
            </div>
        </td>
        <td class="_required">
            <div class="admin__field _required">
                <div class="admin__field-control">
                    <input class="admin__control-text" type="text" name="regionname[<%- data.id %>][name]" maxlength="255">
                </div>
            </div>
        </td>
        <td>
            <button class="action-delete" data-action="remove_row">
                <span ></span>
            </button>
        </td>
    </tr>
</script>
<?php
$data = [
    'counter' => 1
];
?>
<script type="text/x-magento-init">
    {
        "*": {
            "wkUploadRegion":  <?= json_encode($data) ?>
        }
    }
</script>
