<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_CustomerSubaccount
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
/**
 * Order Detail
 *
 * @var \Webkul\CustomerSubaccount\Block\SubaccountOrder\History | \Webkul\CustomerSubaccount\Block\MainOrder\History
 */
?>
<?php $_orders = $block->getOrders(); ?>
<?= /* @noEscape */ $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)): ?>
    <div class="table-wrapper orders-history">
        <table class="data history" id="my-orders-table">
            <caption class="table-caption"><?= /* @noEscape */ $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= /* @noEscape */ $block->escapeHtml(__('Order #')) ?></th>
                    <th scope="col" class="col date"><?= /* @noEscape */ $block->escapeHtml(__('Date')) ?></th>
                    <?= /* @noEscape */ $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col shipping"><?= /* @noEscape */ $block->escapeHtml(__('Ship To')) ?></th>
                    <th scope="col" class="col total"><?= /* @noEscape */ $block->escapeHtml(__('Order Total')) ?></th>
                    <th scope="col" class="col status"><?= /* @noEscape */ $block->escapeHtml(__('Status')) ?></th>
                    <?php if ($block->canViewOrder()) { ?>
                    <th scope="col" class="col actions"><?= /* @noEscape */ $block->escapeHtml(__('Action')) ?></th>
                    <?php }?>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order): ?>
                    <tr>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtmlAttr(__('Order #')) ?>" class="col id"><?= /* @noEscape */ $block->escapeHtml($_order->getRealOrderId()) ?></td>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtmlAttr(__('Date')) ?>" class="col date"><?= /* @noEscape */ /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra): ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= /* @noEscape */ $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtmlAttr(__('Ship To')) ?>" class="col shipping"><?= /* @noEscape */ $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtmlAttr(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtmlAttr(__('Status')) ?>" class="col status"><?= /* @noEscape */ $block->escapeHtml($_order->getStatusLabel()) ?></td>
                        <?php if ($block->canViewOrder()) { ?>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
                            <a href="<?= /* @noEscape */ $block->escapeUrl($block->getViewOrderLink($_order->getId())) ?>" class="action view">
                                <span><?= /* @noEscape */ $block->escapeHtml(__('View Order')) ?></span>
                            </a>
                        </td>
                        <?php }?>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= /* @noEscape */ $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= /* @noEscape */ $block->escapeHtml(__('You have placed no orders.')) ?></span></div>
<?php endif ?>
