<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_CustomerSubaccount
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
/**
 * Quote View with Ajax
 *
 * @var \Webkul\CustomerSubaccount\Block\Quote\View
 */
?>
<?php $quote = $block->getQuote() ?>
<?php $items = $quote->getAllVisibleItems(); ?>
<div class="table-wrapper wkc-cart-data-container">
    <table class="data wkc-quote-table" id="wkc-quote-table" summary="<?= /* @noEscape */ $block->escapeHtml(__('Items')) ?>">
        <caption class="table-caption"><?= /* @noEscape */ $block->escapeHtml(__('Items')) ?></caption>
        <thead>
            <tr>
                <th class="col name"><?= /* @noEscape */ $block->escapeHtml(__('Product Name')) ?></th>
                <th class="col sku"><?= /* @noEscape */ $block->escapeHtml(__('SKU')) ?></th>
                <th class="col price"><?= /* @noEscape */ $block->escapeHtml(__('Price')) ?></th>
                <th class="col qty"><?= /* @noEscape */ $block->escapeHtml(__('Qty')) ?></th>               
                <th class="col price"><?= /* @noEscape */ $block->escapeHtml(__('Subtotal')) ?></th>
            </tr>
        </thead>
        <?php
        $i = 0;
        $count = count($items);
        foreach ($items as $item) {
            if ($item->getParentItem()) {
                continue;
            }
            $productUrl = $block->getProductUrl($item->getProductId());
            $i++;
            $result = [];
            if ($options = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct())) {
                if (isset($options['options'])) {
                    $result = array_merge($result, $options['options']);
                }
                if (isset($options['additional_options'])) {
                    $result = array_merge($result, $options['additional_options']);
                }
                if (isset($options['attributes_info'])) {
                    $result = array_merge($result, $options['attributes_info']);
                }
            }
            $index = 0;
            $prevOptionId = '';
            ?>
            <tbody>
                <tr class="border" id="quote-item-row-<?= /* @noEscape */ $block->escapeHtml($item->getId()) ?>">
                    <?php
                    if ($item->getProductType()=='downloadable') { ?>
                        <td class="col name" data-th="<?= /* @noEscape */ $block->escapeHtml(__('Product Name')); ?>">
                            <a href=<?= /* @noEscape */ $productUrl?> target="_blank"><strong class="product name product-item-name"><?= /* @noEscape */ $block->escapeHtml($item->getName()) ?></strong></a>
                            <?php
                            $options1 = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct());
                            if (isset($options1['options'])):
                                $options = $options1['options'];
                                ?>
                                <dl class="item-options links">
                                    <?php foreach ($options as $option): ?>
                                        <dt><?= /* @noEscape */ $block->escapeHtml($option['label']) ?></dt>
                                        <?php if (!$block->getPrintStatus()): ?>
                                            <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                                            <dd>
                                                <?php if (isset($formatedOptionValue['full_view'])): ?>
                                                    <?= /* @noEscape */ /* @noEscape */ $formatedOptionValue['full_view'] ?>
                                                <?php else: ?>
                                                    <?=/* @noEscape */ $formatedOptionValue['value'] ?>
                                                <?php endif; ?>
                                            </dd>
                                        <?php else: ?>
                                            <dd><?= /* @noEscape */ $block->escapeHtml((isset($option['print_value']) ? $option['print_value'] : $option['value'])) ?></dd>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </dl>
                            <?php endif; ?>
                            <?php /* downloadable */?>
                            <?php if (isset($options1['links']) && !empty($options1['links'])): ?>
                                <dl class="item-options links">
                                    <dt><?= /* @noEscape */ /* @escapeNotVerified */ $block->escapeHtml($block->getLinksTitle($item->getProduct())) ?></dt>
                                    <?php foreach ($block->getLinks($item) as $link): ?>
                                        <dd><?= /* @noEscape */ $block->escapeHtml($link->getTitle()); ?> </dd>
                                    <?php endforeach; ?>
                                </dl>
                            <?php endif; ?>
                            <?php /* EOF downloadable */?>

                            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                            <?php if ($addInfoBlock):?>
                                <?= /* @noEscape */ $addInfoBlock->setItem($item->getOrderItem())->toHtml(); ?>
                            <?php endif; ?>
                            <?= /* @noEscape */ $block->escapeHtml($item->getDescription()) ?>
                        </td>
                        <?php
                    } elseif ($item->getProductType()=='bundle') { ?>
                        <td class="col name" data-th="<?= /* @noEscape */ $block->escapeHtml(__('Product Name')); ?>">
                            <a href=<?= /* @noEscape */ $productUrl?> target="_blank"><strong class="product name product-item-name"><?= /* @noEscape */ $block->escapeHtml($item->getName()) ?></strong></a>
                            <?php if (isset($options['bundle_options'])):
                                ksort($options['bundle_options']);?>
                                <dl class="item-options bundle">
                                <?php foreach ($options['bundle_options'] as $option): ?>
                                    <dt><?= /* @noEscape */ $block->escapeHtml($option['label']) ?></dt>
                                    <dd>
                                        <?php foreach ($option['value'] as $value): ?>
                                            <?= /* @noEscape */  $value['qty'].' x '.$value['title'].' '.$block->formatPrice($value['price']).' ';?>
                                        <?php endforeach; ?>
                                    </dd>
                                <?php endforeach; ?>
                                </dl>
                            <?php endif; ?>
                        </td>
                    <?php } else { ?>
                        <td class="col name" data-th="<?= /* @noEscape */ $block->escapeHtml(__('Product Name')); ?>">
                            <a href=<?= /* @noEscape */ $productUrl?> target="_blank"><strong class="product name product-item-name"><?= /* @noEscape */ $block->escapeHtml($item->getName()) ?></strong></a>
                            <?php if ($options = $result): ?>
                                <dl class="item-options">
                                <?php foreach ($options as $option): ?>
                                    <dt><?= /* @noEscape */ $block->escapeHtml($option['label']) ?></dt>
                                    <?php if (!$block->getPrintStatus()): ?>
                                        <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                                        <dd>
                                            <?php if (isset($formatedOptionValue['full_view'])): ?>
                                                <?= /* @noEscape */ /* @noEscape */ $formatedOptionValue['full_view'] ?>
                                            <?php else: ?>
                                                <?= /* @noEscape */ /* @noEscape */ $formatedOptionValue['value'] ?>
                                            <?php endif; ?>
                                        </dd>
                                    <?php else: ?>
                                        <dd>
                                            <?= /* @noEscape */ /* @noEscape */ nl2br($block->escapeHtml((isset($option['print_value']) ? $option['print_value'] : $option['value']))) ?>
                                        </dd>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                                </dl>
                            <?php endif; ?>
                        </td>
                    <?php }?>
                    <td class="col sku" data-th="<?= /* @noEscape */ $block->escapeHtml(__('SKU')); ?>" style="max-width: 150px;"><?= /* @noEscape */ $block->escapeHtml($item->getSku()) ?></td>
                    <td class="col price" data-th="<?= /* @noEscape */ $block->escapeHtml(__('Price')); ?>">
                        <span class="wkc-item-price">
                            <?= /* @noEscape */ /* @noEscape */ $block->formatPrice($item->getPrice()); ?>
                        </span>
                    </td>
                    <td class="col qty" data-th="<?= /* @noEscape */ $block->escapeHtml(__('Qty')); ?>">
                        <?= /* @noEscape */ $item->getQty()?>
                    </td>
                    <td class="col subtotal" data-th="<?= /* @noEscape */ $block->escapeHtml(__('Subtotal')); ?>"><?= /* @noEscape */ /* @noEscape */ $block->formatPrice($item->getRowTotal());?></td>
                </tr>
            </tbody>
            <?php
        } ?>
    </table>
</div>
