<?php

/** 
* Webkul Software. 
* 
* @category Webkul 
* @package Webkul_WebApplicationFirewall
* @author Webkul
* @copyright Copyright (c) WebkulSoftware Private Limited (https://webkul.com) 
* @license https://store.webkul.com/license.html 
* 
*/
// @codingStandardsIgnoreFile

/** @var \Webkul\WebApplicationFirewall\Block\Adminhtml\System\Config\SendPasswordReset $block */

?>
<div id="reset_area">
<?= /** @noEscape */ $block->getButtonHtml() ?>
</div>

<span class="collect-indicator" id="indicator_span">
    <span id="sending" hidden="hidden">
        <img alt="Sending" style="margin:0 5px"
             src="<?= /** @noEscape */ $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
        <?= /** @noEscape */ __('Sending...') ?>
    </span>
</span>

<script>
require([
    'jquery',
    'prototype'
], function (jQuery) {
    sendPasswordReset = function () {
        var self = this;
        new Ajax.Request('<?= /** @noEscape */ $block->getAjaxUrl() ?>', {
            parameters: {},
            loaderArea: false,
            asynchronous: true,
            onCreate: function () {
                // jQuery('#installed').hide();
                jQuery('#sending').show();
                // jQuery(self).prop("disabled", true);
            },

            onSuccess: function(response) {
                if (!response.error) {
                    // jQuery('#installed').show();
                } else {
                    $('<div class="message message-error" style="margin-bottom: 5px;color:red"><p>' + response.message + '</p></div>').insertBefore(jQuery(self));
                }
                
                jQuery('#sending').hide();
            },
        });
    };
    if ($('reset_password_button')) {
        $('reset_password_button').observe('click', sendPasswordReset);
    }
});

</script>