<?php
/**
 * @category   Webkul
 * @package    Webkul_MpPushNotification
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */

$viewModel = $block->getViewModel();
$helper = $viewModel->getMarketplaceHelper();
$isPartner = $helper->isSeller();
$secureurl=['_secure' => $block->getRequest()->isSecure()];
$form_action="mppushnotification/templates/save";
?>
<?php if ($isPartner == 1): ?>
    <form action="<?= /* @noEscape */$block->getUrl($form_action, $secureurl); ?>"
     enctype="multipart/form-data" method="post" id="new-template" 
     data-form="new-template" data-mage-init='{"validation":{}}'>
    <div class="wk-mp-design" id="wk-bodymain">
        <fieldset class="fieldset info wk-mp-fieldset">
            <legend class="legend">
                <span><?= /* @noEscape */  __('Save Template') ?></span>
                <button class="button wk-mp-btn" title="<?= /* @noEscape */  __('Save') ?>"
                 type="submit" id="save-btn">
                    <span><span><?= /* @noEscape */  __('Save') ?></span></span>
                </button>
            </legend>            
            <?= /* @noEscape */  $block->getBlockHtml('formkey')?>
            <div class="field required">
                <label class="label"><?= /* @noEscape */  __('Title') ?>:</label>
                <div class="control">
                    <input type="text" 
                    class="required-entry input-text validate-alphanum-with-spaces"
                     name="title" id="title"/>
                </div>
            </div>
            <div class="field required">
                <label class="label"><?= /* @noEscape */  __('Message') ?>:</label>
                <div class="control">
                    <input type="text" class="required-entry input-text validate-alphanum-with-spaces"
                    name="message" id="message"/>
                </div>
            </div>
            <div class="field required">
                <label class="label"><?= /* @noEscape */  __('Redirect Url') ?>:</label>
                <div class="control">
                    <input type="url" class="required-entry input-text" name="url" id="name"/>
                </div>
            </div>
            <div class="field required">
                <label class="label"><?= /* @noEscape */  __('Tags') ?>:</label>
                <div class="control">
                    <input type="text" class="required-entry input-text validate-alphanum-with-spaces"
                    name="tags" id="tags"/>
                </div>
            </div>
            <div class="field required">
                <label class="label"><?= /* @noEscape */  __('Logo') ?>:</label>
                <div class="control">
                    <div class="wk-ap-ap-img-box">
                     
                        <img  id="imgsrc" height="50px" width="50px" style="display:none;" src="">
                    </div>
                    <span class="file-uploader-spinner"></span>
                    <input type="file" class="required-entry input-text validate-fileextensions"
                     name="logo" id="logo"  accept="image/*"/>
                   
                </div>
            </div>

        </fieldset>
    </div>        
</form>
<?php else: ?>
    <h2 class="wk-mp-error-msg">
        <?= /* @noEscape */  __("To Become Seller Please Contact to Admin."); ?>
    </h2>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "*": {
            "templateform": {}
        }
    }
</script>