<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Pwa
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<meta name="theme-color" content="<?= /* @noEscape */   $block->getThemeColor(); ?>">
<link href="<?= /* @noEscape */   $block->getUrl(); ?>manifest.json" rel="manifest" />
