<?php
/**
 * @category   Webkul
 * @package    Webkul_MpPushNotification
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */


$viewModel = $block->getViewModel();
$helper = $viewModel->getMarketplaceHelper();
$template = $block->getTemplateData();
$isPartner = $helper->isSeller();

?>
<?php if ($isPartner == 1): ?>
<div class="wk-mp-design">
    <fieldset class="fieldset info wk-mp-fieldset">
        <legend class="legend"><span><?= /* @noEscape */  __('Complete View Of Template') ?></span></legend>
        <div class="wk-mp-order-info-box wk-mp-push-info-box">
            <div>
                <div class="box">
                    <div class="box-title">
                        <h2><?= /* @noEscape */  __('Template Information') ?></h2>
                    </div>
                    <div class="box-content">
                        <div class="wk_row">
                            <strong class="label"><?= /* @noEscape */  __('Title')?> : </strong>
                            <span class="value"><?= /* @noEscape */  $template['title']; ?></span>
                        </div>
                        <div class="wk_row">
                            <strong class="label"><?= /* @noEscape */  __('Message')?> : </strong>
                            <span class="value"><?= /* @noEscape */  $template['message']; ?></span>
                        </div>
                        <div class="wk_row">
                            <strong class="label"><?= /* @noEscape */  __('Redirect Url')?> : </strong>
                            <span class="value"><?= /* @noEscape */  $template['url']; ?></span>
                        </div>
                        <div class="wk_row">
                            <strong class="label"><?= /* @noEscape */  __('Tags')?> : </strong>
                            <span class="value"><?= /* @noEscape */  $template['tags']; ?></span>
                        </div>
                        <div class="wk_row">
                            <strong class="label"><?= /* @noEscape */  __('Date')?> : </strong>
                            <span class="value"><?= /* @noEscape */  $template['created_at']; ?></span>
                        </div>
                        <div class="wk_row wk_row_logo ">
                            <strong class="label"><?= /* @noEscape */  __('Logo')?> : </strong>
                            <span class="value">
                                <img src="<?= /* @noEscape */  $block->getImageView($template['logo']); ?>" 
                                height="100px" width="100px" />
                                </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>
</div>
<?php else: ?>
    <h2 class="wk-mp-error-msg">
        <?= /* @noEscape */  __("To Become Seller Please Contact to Admin."); ?>
    </h2>
<?php endif; ?>