<?php
/**
 * Webkul_MpAuction deal list block.
 * @category  Webkul
 * @package   Webkul_MpAuction
 * @author    Webkul
 * @copyright Copyright (c)  Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

/** @var $block \Webkul\Marketplace\Block\Product\Productlist */
$mpAuctionViewmodel = $block->getMpAuctionViewmodel();
$helper = $mpAuctionViewmodel->getMarketplaceHelper();
$paramData = $block->getRequest()->getParams();
$filter = '';

if (isset($paramData['s'])) {
    $filter = $paramData['s'] != '' ? $paramData['s'] : '';
}
$auctionTimeOffset = [];
$_products_coll = $block->getAllProducts();
if ($helper->isSeller() && $block->isAuctionEnable()) { ?>
<div class="wk-mp-design">
    <fieldset class="fieldset info wk-mp-fieldset">
        <legend class="legend">
            <span><?= /* @noEscape */ __('My Auction Product List') ?></span>
        </legend>
        <div class="grid">
            <div class="hor-scroll">
                <form action="<?= /* @noEscape */ $block->getUrl('mpauction/account/auctionlist/', ['_secure' => $block->getRequest()->isSecure()])?>" method="get" id="form-productlist-filter"  name="formProductlistFilter" data-mage-init='{"validation":{}}'>
                    <table cellspacing="0" class="border wk-mp-list-table">
                        <thead>
                            <tr id="wk-mp-tr-heading">
                                <th><span><?= /* @noEscape */ __('Product Name') ?></span></th>
                                <th><span>&nbsp;</span></th>
                            </tr>
                        </thead>
                        <tbody class="wk-mp-body">
                            <tr>
                                <td>
                                    <input type="text" class="input-text" name="s" placeholder='<?= /* @noEscape */ __('Search by product name') ?>' value="<?= /* @noEscape */ $block->escapeHtml($filter)?>"/>
                                </td>
                                <td>
                                    <button class="button" title="Save" type="submit">
                                        <span><span><span><?= /* @noEscape */ __('Submit') ?></span></span></span>
                                    </button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </form>
                <?php if ($_products_coll && count($_products_coll)): ?>
                    <form action="<?= /* @noEscape */ $block->getUrl('mpauction/account/massdisable', ['_secure' => $block->getRequest()->isSecure()]) ?>" method="post" id="form-productlist-massdisable" name="formProductlistMassDisable" data-mage-init='{"validation":{}}' class="table-wrapper">
                        <?= /* @noEscape */ $block->getBlockHtml('formkey')?>
                        <?= /* @noEscape */ $block->getBlockHtml('seller.formkey')?>
                        <button class="button" title="<?= /* @noEscape */ __('Cancel Auction') ?>" type="submit" id="mass-delete-butn">
                            <span>
                                <span><?= /* @noEscape */ __('Cancel Auction') ?></span>
                            </span>
                        </button>
                        <table cellspacing="0" class="table data border wk-mp-list-table wk-mp-list-container-table">
                            <thead>
                                <tr class="wk-content">
                                    <th class="wk-check-first-td">
                                        <span>
                                            <input type="checkbox" name="mpselecctall" value="all" id="mpauctionselecctall"/>
                                        </span>
                                    </th>
                                    <th class="wk-first-td name">
                                        <span class="label">
                                            <?= /* @noEscape */ __('Auction Product')?>
                                        </span>
                                    </th>
                                    <th class="wk-first-td qty">
                                        <span class="label">
                                            <?= /* @noEscape */ __('Quantity')?>
                                        </span>
                                    </th>
                                    <th class="wk-first-td">
                                        <span class="label name">
                                            <?= /* @noEscape */ __('Auction Date')?>
                                        </span>
                                    </th>
                                    <th class="wk-first-td options">
                                        <span class="label name">
                                            <?= /* @noEscape */ __('Options')?>
                                        </span>
                                    </th>
                                    <th class="wk-first-td status">
                                        <span class="label name">
                                        <?= /* @noEscape */ __('Auction Status')?>
                                        </span>
                                    </th>
                                    <th class="wk-first-td">
                                        <span class="label name">
                                        <?= /* @noEscape */ __('Product Sold')?>
                                        </span>
                                    </th>
                                    <th class="wk-first-td">
                                        <span class="label name">
                                            <?= /* @noEscape */ __('Bid Detail')?>
                                        </span>
                                    </th>
                                    <th>
                                        <span class="label">
                                            <?= /* @noEscape */ __('Action')?>
                                        </span>
                                    </th>                        
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 0;
                                foreach ($_products_coll as $aucDetail) {
                                    $i++;
                                    $products = $block->getProductDetail($aucDetail->getProductId());
                                    $imageUrl = $block->imageHelperObj()->init($products, 'product_page_image_small')->setImageFile($products->getFile())->getUrl();
                                    ?>
                                    <tr class="wk-row-view <?= /* @noEscape */ $class = ($i == count($block->getAllProducts()))? 'wk-last_tr':''?>">
                                        <td data-th="Select" class="col wk-check-first-td">
                                            <span>
                                                <input type="checkbox" name="auction_mass_disable[]" class="mpcheckbox" value="<?= /* @noEscape */ $aucDetail->getEntityId(); ?>"/>
                                            </span>
                                        </td>
                                        <td data-th="<?= /* @noEscape */ __('Auction Product') ?>" class="col wk-first_td">
                                            <input type="hidden" class="hidden-id" value="<?= /* @noEscape */ $products->getEntityId(); ?>" />
                                            <div class="label name" title="<?= /* @noEscape */ $products->getName(); ?>">
                                                <div class="wk-pro-divide1">
                                                    <img src="<?= /* @noEscape */ $imageUrl?>" class="image" />
                                                </div>
                                                <div class="wk-pro-divide2">
                                                    <div style="width:100%;">
                                                        <?php if ($products->getStatus()==1 && $products->getVisibility()!=1) { ?>
                                                            <a href="<?= /* @noEscape */ $products->getProductUrl()?>" target="blank">
                                                        <?php }?>
                                                            <?= /* @noEscape */ $products->getName();?>
                                                        <?php if ($products->getStatus()==1 && $products->getVisibility()!=1) { ?>
                                                            </a>
                                                        <?php }?>
                                                    </div>
                                                    <div style="width:100%;float:left;">
                                                        <div style="font-size:10px;">
                                                            <b><?= /* @noEscape */ __('Starting Price :')?></b>
                                                            <?= /* @noEscape */ $block->getFormatedPrice($aucDetail->getStartingPrice(), $helper->getCurrencySymbol());?>
                                                            </div>
                                                        <div style="font-size:10px;">
                                                            <b><?= /* @noEscape */ __('Reserve Price :')?></b>
                                                            <?= /* @noEscape */ $block->getFormatedPrice($aucDetail->getReservePrice(), $helper->getCurrencySymbol());?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                        <td data-th="<?= /* @noEscape */ __('Quantity') ?>" class="col">
                                            <div>
                                                <b><?= /* @noEscape */ __('Min : ')?></b>
                                                <?= /* @noEscape */ $aucDetail->getMinQty()?>
                                            </div>
                                            <div>
                                                <b><?= /* @noEscape */ __('Max : ')?></b>
                                                <?= /* @noEscape */ $aucDetail->getMaxQty()?>
                                            </div>
                                        </td>
                                        <td data-th="<?= /* @noEscape */ __('Auction Date') ?>" class="col">
                                            <div><b><?= /* @noEscape */ __('Start :')?></b>
                                                <span id="start_auction_time<?= /* @noEscape */ $aucDetail->getEntityId(); ?>"><?= /* @noEscape */ $block->getDateTimeAsLocale($aucDetail->getStartAuctionTime());
                                                $auctionTimeOffset[$aucDetail->getEntityId()]['start_auction_time'] = $block->converToTz($aucDetail->getStartAuctionTime()); ?></span>
                                            </div>
                                            <div><b><?= /* @noEscape */ __('Stop :')?></b>
                                                <span id="stop_auction_time<?= /* @noEscape */ $aucDetail->getEntityId(); ?>"><?= /* @noEscape */ $block->getDateTimeAsLocale($aucDetail->getStopAuctionTime());
                                                $auctionTimeOffset[$aucDetail->getEntityId()]['stop_auction_time'] = $block->converToTz($aucDetail->getStopAuctionTime());
                                                ?></span>
                                            </div>
                                        </td>
                                        <td data-th="<?= /* @noEscape */ __('Options') ?>" class="col">
                                            <div>
                                                <b><?= /* @noEscape */ __('Increment :')?></b>
                                                <?= /* @noEscape */ $block->getStatusLabel($aucDetail->getIncrementOpt())?>
                                            </div>
                                            <div><b><?= /* @noEscape */ __('Auto Bid :')?></b>
                                                <?= /* @noEscape */ $block->getStatusLabel($aucDetail->getAutoAuctionOpt())?>
                                            </div>
                                        </td>
                                        <td data-th="<?= /* @noEscape */ __('Auction Status') ?>" class="col"><?= /* @noEscape */ $block->getAuctionStatusLabel($aucDetail->getAuctionStatus())?></td>
                                        <td data-th="<?= /* @noEscape */ __('Product Sold') ?>" class="col"><?= /* @noEscape */ $block->getAucProSoldStatus($aucDetail->getEntityId())?></td>
                                        <td data-th="<?= /* @noEscape */ __('Bid Detail') ?>" class="col">
                                            <a href="<?= /* @noEscape */ $block->getBidDetailUrl($aucDetail->getEntityId())?>" class="button" ><?= /* @noEscape */ __('View') ?></a>
                                        </td>
                                        <td data-th="<?= /* @noEscape */ __('Action') ?>" class="col">
                                            <a href="<?= /* @noEscape */ $block->getAddAuctionUrl($aucDetail->getEntityId())?>" class="button" ><?= /* @noEscape */ $aucDetail->getAuctionStatus()? __('Edit') : __('Detail') ?></a>
                                        </td>                        
                                    </tr>
                                    <?php
                                }?>
                            </tbody>
                        </table>
                    </form>                
                <?php else: ?>
                    <div class="wk-emptymsg">
                        <?= /* @noEscape */ __('No Product Available') ?>
                    </div>
                <?php endif ?>                    
            </div>
        </div>
        <?php if ($block->getPagerHtml()): ?>
            <div class="order-products-toolbar toolbar bottom"><?= /* @noEscape */ $block->getPagerHtml(); ?></div>
        <?php endif ?>    
    </fieldset>    
    <div class="buttons-set">
        <p class="back-link">
            <a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?= /* @noEscape */ __('Back') ?></a>
        </p>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "sellerauctionlist": {
                "zone": "<?= /* @noEscape */ $block->getConfigTimeZone() ?>",
                "timeOffset" : <?= /* @noEscape */ json_encode($auctionTimeOffset); ?>
            }
        }
    }
</script>
<?php } else { ?>
<h3><?= /* @noEscape */ __('Add auction not allowed')?></h3>
<?php } ?>