<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpWholesale
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
$data = $block->getLeadDetails();?>
<table class="wk-lead-admin-table">
<?php foreach ($data as $index => $value): ?>
    <tr>
        <td style="text-align:right; font-weight:700; padding-right:20px">
            <?= /* @noEscape */ __($index); ?>
        </td>
        <td>
            <?php if ($value !="") { echo $block->escapeHtml($value);
            } else {echo /* @noEscape */ "-";} ?>
        </td>
    </tr>
<?php endforeach; ?>
</table>

<style>
    .wk-lead-admin-table{
        width: 100%;
        margin-top:20px;

    }
    .wk-lead-admin-table tr {
        line-height: 2;
    }
</style>
