<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAdvertisementManager
 * @author    Webkul
 * @copyright Copyright (c)   Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
    $blockData = $block->getCurrentBlock();
    $blockId = $blockData->getId() == null?null:$blockData->getId();
    $requiredClassForFileUploadInput = "required-entry input-text required-entry _required";
    $mediaUrl = "";
if ($blockId) {
    $requiredClassForFileUploadInput = "";
    $mediaUrl = $block->getMediaUrl().'webkul/MpAdvertisementManager/'.
    $blockData['seller_id'].'/'.$blockData['id'].'/'.trim(str_replace(" ", "_", $blockData['image_name']));
}

    $height = $block->getHeightConfig()==""?'300px':$block->getHeightConfig();
?>
<form
    action="<?=
        $block->escapeUrl($block->getUrl(
            'mpads/block/save',
            ['_secure' => $block->getRequest()->isSecure()]
        )) ?>"
    enctype="multipart/form-data"
    method="post"
    id="block-form"
    data-mage-init='{"validation":{}}'
>
    <div>
        <input
            type="hidden"
            name="id"
            value="<?= $block->escapeHtml($blockId); ?>"
        >
    </div>
    <div class="wk-mp-design">
        <fieldset class="fieldset info wk-mp-fieldset">
            <legend class="legend">
                <span><?= $block->escapeHtml(__('Block Form')) ?></span>
                <button
                    class="button primary action wk-mp-btn"
                    title="Save"
                    type="submit"
                    disabled="disabled"
                >
                <span><span><?= $block->escapeHtml(__('Save')) ?></span></span>
                </button>
                <?php if ($blockId) { ?>
                <a
                    class="button primary action wk-mp-btn"
                    title="Delete"
                    href="<?=
                        $block->escapeUrl($block->getUrl(
                            'mpads/block/delete',
                            [
                            'blockId' => $blockData->getId(),
                            '_secure' => $block->getRequest()->isSecure()
                            ]
                        ));
                            ?>"
                >
                    <span><span><?= $block->escapeHtml(__('Delete')) ?></span></span>
                </a>
                <?php } ?>
            </legend>
            <?= /* @noEscape */  $block->getBlockHtml('seller.formkey')?>
            <?= /* @noEscape */  $block->getBlockHtml('formkey')?>
            <div class="field required">
                <label class="label"><?= $block->escapeHtml(__('Title')) ?>:</label>
                <div class="control">
                    <input
                        name="title"
                        id="title"
                        class="required-entry input-text required-entry _required validate-no-html-tags"
                        type="text"
                        value="<?= $block->escapeHtml($blockData->getTitle() == null?'':$blockData->getTitle()); ?>" />
                </div>
            </div>
            <div class="field required">
                <label class="label"><?= $block->escapeHtml(__('Image')) ?>:</label>
                <div class="control" >
                    <div style="border: 2px dotted #ccc;clear: both;display: table;margin-bottom: 2px;
                    padding: 5px 0 0;position: relative;">
                        <div id="wk_mpads_imageupload" 
                        style="background: #fff none repeat scroll 0 0;border: 1px solid #ccc;
                        box-sizing: border-box;display: inline-block;float: left;
                        height: 125px;margin: 0 0.8rem 6px;overflow: hidden;position: relative;width: 125px;
                        background-image:url(<?= $block->escapeUrl($mediaUrl) ;?>) ;
                        background-size:cover;cursor: pointer;">
                            <p id="wk_mpads_imageupload_default_message" 
                            style="bottom: 0;color: #008bdb;font-size: 1.1rem;
                            left: 0;line-height: 1.333;margin-bottom: 30%;padding: 0 1rem;
                            position: absolute;right: 0;text-align: center;">
                                <span><?= $block->escapeHtml(__("Click here to add images.")) ?></span>
                            </p>
                        </div>
                    </div>
                    <input type="file" name="content" id="content" accept="image/*" 
                    class="<?= $block->escapeHtml($requiredClassForFileUploadInput); ?>" style="visibility:hidden;"/>
                    <div class="admin__field-note">
                        <span><?= $block->escapeHtml(__("For better appearance please 
                        upload image of width $height")) ?></span>
                    </div>
                </div>
            </div>
            <div class="field required">
                <label class="label"><?= $block->escapeHtml(__('Url')) ?>:</label>
                <div class="control">
                <input type="text" name="url" id="ads_url" 
                class="required-entry input-text required-entry _required validate-no-html-tags" 
                value="<?= $block->escapeUrl($blockData->getUrl() == null?'':$blockData->getUrl()); ?>" 
                data-validate="{required:true, 'validate-url':true}"/>
                </div>
            </div>
        </fieldset>
    </div>
</form>

<script type="text/x-magento-init">
    {
        "*":{
            "adsManager":{
                "blockEditData": {
                    "wysywygConfig":<?= /* @noEscape */ $block->getWysiwygConfig(); ?>
                }
            }
        }
    }
</script>
