<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAdvertisementManager
 * @author    Webkul
 * @copyright Copyright (c)   Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
    $filter = $block->getRequest()->getParam('title')?$block->getRequest()->getParam('title'):false;
    
?>
<div class="wk-mp-design mpads-block-manager-cont">
    <fieldset class="fieldset info wk-mp-fieldset">

        <legend class="legend">
            <a class="action primary wk-mp-btn" href=" <?=
             $block->escapeUrl($block->getUrl('mpads/block/edit', ['_secure'
             => $block->getRequest()->isSecure()])) ?>">
                <span><span> 
                <?=
                    $block->escapeHtml(__('Ads Blocks'))
                ?>
                </span></span>
            </a>
        </legend>
        <div class="grid">
                <div class="hor-scroll">
                    <form action="<?= $block->escapeUrl($block->getUrl('mpads/block', ['_secure'
                    => $block->getRequest()->isSecure()]))?>" method="get" id="form-adsblock-filter"
                      name="form_ads_block_filter" data-mage-init='{"validation":{}}'>
                    <table cellspacing="0" class="border wk-mp-list-table">
                        <thead>
                            <tr id="wk-mp-tr-heading">
                                <th><span><?= $block->escapeHtml(__('Block Title')) ?></span></th>
                                <th><span>&nbsp;</span></th>
                            </tr>
                        </thead>
                        <tbody class="wk-mp-body">
                            <tr>
                                <td>
                                    <input type="text" class="input-text" name="title"
                                    placeholder='<?= $block->escapeHtml(__('Search by product name')) ?>' 
                                    value="<?= $block->escapeHtml($filter == false?'':$filter); ?>"/>
                                </td>
                                <td>
                                    <button class="button" title="Save" type="submit">
                                        <span><span><span><?= $block->escapeHtml(__('Submit')) ?>
                                        </span></span></span>
                                    </button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    </form>
            </div>    
            <form action="<?= $block->escapeUrl($block->getUrl(
                'mpads/block/delete',
                [
                            '_secure' => $block->getRequest()->isSecure()
                            ]
            ));
?>" method="post" id="form-blocklist-massdelete" name="form-blocklist-massdelete" 
            data-mage-init='{"validation":{}}'>
                <?= /* @noEscape*/  $block->getBlockHtml('seller.formkey')?>
                <?= /* @noEscape*/  $block->getBlockHtml('formkey')?>
                <button class="button" title="<?= $block->escapeHtml(__('Delete Ad Blocks'))
                ?>" type="submit"  id="mass-delete-butn">
                    <span><span><?= $block->escapeHtml(__('Delete Ad Blocks')) ?></span></span>
                </button>
                <?php
                $count = $block->getCollection()->getSize();
                $i=0;
                if ($count > 0) {
                    $collection = $block->getCollection();
                    ?>
                    <table 
                        cellspacing="0" 
                        class="border wk-mp-list-table wk-mp-list-container-table"
                    >
                        <thead>
                            <tr class="wk-content">
                                <th class="wk-check-first-td">
                                    <span>
                                        <input type="checkbox" name="mpselecctall" value="all" id="mpselecctall"/>
                                    </span>
                                </th>
                                <th>
                                    <?=
                                        $block->escapeHtml(__('Id'));
                                    ?>
                                </th>
                                <th>
                                    <?=
                                        $block->escapeHtml(__('Title'));
                                    ?>
                                </th>
                                <th>
                                    <?=
                                        $block->escapeHtml(__('Created At'));
                                    ?>
                                </th>
                                <th>
                                    <?=
                                        $block->escapeHtml(__('Updated At'));
                                    ?>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($collection as $adsblock) { $i ++; ?>
                            <tr 
                            title="<?=
                                $block->escapeUrl($block->getUrl(
                                    'mpads/block/edit',
                                    [
                                    'id' => $adsblock->getId(),
                                    '_secure' => $block->getRequest()->isSecure()
                                    ]
                                ));
                                    ?>" 
                            class="wk-row-view 
                                <?= $block->escapeHtml($class = ($i == $count))? 'wk-last_tr':''?>"
                            style="cursor: pointer;"
                            >
                                <td class="wk-check-first-td">
                                    <span>
                                        <input type="checkbox" name="blockId[]" 
                                        class="mpcheckbox checkbox required" value="<?=
                                        $block->escapeHtml($adsblock->getId()); ?>"/>
                                    </span>
                                </td>
                                <td>
                                    <?=
                                        $block->escapeHtml($adsblock->getId());
                                    ?>
                                </td>
                                <td>
                                    <?=
                                        $block->escapeHtml($adsblock->getTitle());
                                    ?>
                                </td>
                                <td>
                                    <?=
                                        $block->escapeHtml($adsblock->getCreatedAt());
                                    ?>
                                </td>
                                <td class="wk-list-th-display">
                                    <?=
                                        $block->escapeHtml($adsblock->getUpdatedAt());
                                    ?>
                                </td>
                            </tr>
                    <?php } ?>
                        </tbody>
                    </table>
                </form>
                    <?=  /*  @noEscape */  $block->getPagerHtml(); ?>
            <?php } else {
                    ?>
                <div class="emptymsg">
                    <?=
                        $block->escapeHtml(__('No ad blocks added yet'))
                    ?>
                </div>
                    <?php
            } ?>
        </div>
    </fieldset>
</div>

<script type="text/x-magento-init">
    {
        "*":{
            "adsManager":{
                "blockData": {
                    "rowClass":"tr.wk-row-view"
                }
            }
        }
    }
</script>