<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_AbandonedCart
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
    $adminName = strip_tags($block->getAdminNameFromConfig());
    $adminEmail = strip_tags($block->getEmailFromConfig());
?>
<div class="popup_background" id="popup_background" style="display:none">
    <form id="wk-abandon-cart-mail-form"
    action="<?= $block->escapeUrl($block->getUrl('abandonedcart/customemail/send'))?>" 
    enctype="multipart/form-data" method="post">
        <div class="admin__field _required">
            <input type="hidden" name="cartId" id="customerId" value=<?= /* @noEscape */ $block->getcartId();?>>
            <input name="form_key" type="hidden" value="<?= /* @noEscape */ $block->getFormKey() ?>" />
            <label class="admin__field-label">
                <span><?= /* @noEscape */ __('Admin Name in Email'); ?></span>
            </label>
            <div class="admin__field-control">
                <input id="adminName" value="<?= /* @noEscape */ $adminName;?>"
                class="admin__control-text" type="text" name="adminName" maxlength="255" required>
            </div>
        </div>
        <div class="admin__field _required">
            <label class="admin__field-label">
                <span ><?= /* @noEscape */ __('Admin Email Id'); ?></span>
            </label>
            <div class="admin__field-control">
                <input id="adminEmail" value="<?= /* @noEscape */$adminEmail;?>"
                class="admin__control-text" type="email" name="adminEmail" maxlength="255" required>
            </div>
        </div>
        <div class="admin__field _required">
            <label class="admin__field-label">
                <span><?= /* @noEscape */ __("Mail body");?></span>
            </label>
            <div class="admin__field-control">
                <textarea name="mailBody" id="mailBody">
                </textarea>
            </div>
            <p style="display:none; color:red; float:left" class="wk-required-warning">
            <?= /* @noEscape */ __('This is a required field');?>
        </div>
    </form>
    <button class="primary" id="submit_mail"><?= /* @noEscape */ __('Send Mail'); ?></button>
    <button type="default" class="primary" id="reset_popup" style="margin-right:10px">
        <?= /* @noEscape */ __('Reset'); ?>
    </button>
</div>
