<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_AbandonedCart
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>

<?php $data = $block->getMailDetails(); ?> 
<div id="element">
    <?php
    if ($data->getSize()):
        foreach ($data as $email):
            ?>
    <div style="margin-bottom:20px">
        <div data-role="collapsible">
            <div data-role="trigger" class="heading">
                <span><?= /* @noEscape */__("Email Sent by ").$email->getSentBy().' on '. $email->getSentOn();?></span>
            </div>
        </div>
        <div data-role="content" class="content"><?= /* @noEscape */ $email->getMailContent();?></div>
    </div>
    <?php endforeach;
else: ?>
<p><?= /* @noEscape */ __('No data to display'); ?></p>
    <?php endif;?> 
</div>