<?php
/**
 * Webkul_MpDailyDeals View On Category.
 * @category  Webkul
 * @package   Webkul_MpDailyDeals
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

?>
<script>window.Mpdailyurl = '<?= /* @noEscape */ $block->getUrl("mpdailydeal/index/gettimes") ?>';</script>
<script type="text/x-magento-init">
    {
        "body": {
             "viewondeal": {}
        }
    }
</script>
