<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_CustomerSubaccount
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

if ($block->isForcedAddress()) { ?>
<script type="text/x-magento-init">
{
    "*" : {
        "multishippingcheckout": ""
    }
}
</script>
<?php } ?>