<?php
/**
 * @category   Fifo
 * @package    Fifo_CreditTerms
 * @author     abdulmalik422@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Fifo\CreditTerms\Controller\Adminhtml\Applications;

class Edit extends \Fifo\CreditTerms\Controller\Adminhtml\Applications
{

    public function execute()
    {
        $id = $this->getRequest()->getParam('id');
        $model = $this->_objectManager->create('Fifo\CreditTerms\Model\CreditTerms');

        if ($id) {
            $model->load($id);
            if (!$model->getId()) {
                $this->messageManager->addError(__('This Applications no longer exists.'));
                $this->_redirect('fifo_creditterms/*');
                return;
            }
        }
        // set entered data if was error when we do save
        $data = $this->_objectManager->get('Magento\Backend\Model\Session')->getPageData(true);
        if (!empty($data)) {
            $model->addData($data);
        }
        $this->_coreRegistry->register('current_fifo_creditterms_applications', $model);
        $this->_initAction();
        $this->_view->getLayout()->getBlock('applications_applications_edit');
        $this->_view->renderLayout();
    }
}
