<?php
/**
 * @category   Fifo
 * @package    Fifo_CreditTerms
 * @author     abdulmalik422@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Fifo\CreditTerms\Setup;

use Magento\Framework\Setup\InstallSchemaInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\SchemaSetupInterface;

/**
 * @codeCoverageIgnore
 */
class InstallSchema implements InstallSchemaInterface
{
    /**
     * {@inheritdoc}
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    public function install(SchemaSetupInterface $setup, ModuleContextInterface $context)
    {
		$installer = $setup;
		$installer->startSetup();

		$definitionTableName = $installer->getTable('fifo_creditterms_definitions');
        if ($installer->getConnection()->isTableExists($definitionTableName) != true) {
            /**
             * Creating table fifo_creditterms_definitions
             */
            $table = $installer->getConnection()->newTable(
                $definitionTableName
            )
                ->addColumn(
                    'creditterms_definition_id',
                    \Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
                    null,
                    ['identity' => true, 'unsigned' => true, 'nullable' => false, 'primary' => true],
                    'Definition Id'
                )
                ->addColumn(
                    'status',
                    \Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
                    1,
                    ['nullable' => false,'default' => 0],
                    'Payment Terms'
                )
                ->addColumn(
                    'terms_name',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => true],
                    'Terms Name'
                )
                ->addColumn(
                    'terms_description',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => true,'default' => null],
                    'Description of Terms'
                )
                ->addColumn(
                    'payment_terms',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => false,'default' => null],
                    'Payment Terms'
                )
                ->addColumn(
                    'credit_limit',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => true,'default' => null],
                    'Credit Limit'
                )
                ->addColumn(
                    'type',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => true,'default' => null],
                    'Type'
                )
                ->addColumn(
                    'created_at',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TIMESTAMP,
                    null,
                    ['nullable' => false],
                    'Created At'
                )->setComment(
                    'Fifo CreditTerms Definition Table'
                );
            $installer->getConnection()->createTable($table);
        }

        $applicationTableName = $installer->getTable('fifo_creditterms_applications');
        if ($installer->getConnection()->isTableExists($applicationTableName) != true) {
            /**
             * Creating table fifo_creditterms_applications
             */
            $table = $installer->getConnection()->newTable(
                $applicationTableName
            )
                ->addColumn(
                    'creditterms_application_id',
                    \Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
                    null,
                    ['identity' => true, 'unsigned' => true, 'nullable' => false, 'primary' => true],
                    'Application Id'
                )
                ->addColumn(
                    'application_status',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => true,'default' => null],
                    'Application Status'
                )
                ->addColumn(
                    'cr_number',
                    \Magento\Framework\DB\Ddl\Table::TYPE_INTEGER,
                    1,
                    ['nullable' => false,'default' => 0],
                    'Commercial Registration Number'
                )
                ->addColumn(
                    'company_name',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => true],
                    'Company Name'
                )
                ->addColumn(
                    'restaurant_name',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => true,'default' => null],
                    'Restaurant Name'
                )
                ->addColumn(
                    'number_of_branches',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => false,'default' => null],
                    'Number of branches'
                )
                ->addColumn(
                    'location',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => true,'default' => null],
                    'Location'
                )
                ->addColumn(
                    'region',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => true,'default' => null],
                    'Region'
                )->addColumn(
                    'owner_name',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => true,'default' => null],
                    'Owner name'
                )->addColumn(
                    'contact_person_name',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => true,'default' => null],
                    'Contact Person Name'
                )->addColumn(
                    'contact_number',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => true,'default' => null],
                    'Contact Number'
                )->addColumn(
                    'contact_email',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => true,'default' => null],
                    'Contact Email'
                )->addColumn(
                    'buyer_credit_terms',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TEXT,
                    255,
                    ['nullable' => true,'default' => null],
                    'Buyer Credit terms'
                )
                ->addColumn(
                    'created_at',
                    \Magento\Framework\DB\Ddl\Table::TYPE_TIMESTAMP,
                    null,
                    ['nullable' => false],
                    'Created At'
                )->setComment(
                    'Fifo CreditTerms Definition Table'
                );
            $installer->getConnection()->createTable($table);
        }

		$installer->endSetup();
	}
}
