<?php
/**
 * @category   Webkul
 * @package    Webkul_MpPushNotification
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */
/** @var $block \Webkul\Marketplace\Block\Product\Productlist */

$viewModel = $block->getViewModel();
$helper = $viewModel->getMarketplaceHelper();
$paramData = $block->getRequest()->getParams();
$usersCollection = $block->getCollection();
$templateCollection = $block->getSellerTemplatesList();
$c_action="mppushnotification/users/massdelete";
$secureurl=['_secure' => $block->getRequest()->isSecure()];

?>    
<div class="wk-mp-design">
    <fieldset class="fieldset info wk-mp-fieldset">
        <legend class="legend">
            <span><?= /* @noEscape */  __('Registered Users For Push Notification') ?></span>
        </legend>
        <div class="grid">
            <div class="hor-scroll">
                <form action="<?= /* @noEscape */  $block->getUrl(
                    'mppushnotification/users/index',
                    ['_secure' => $block->getRequest()->isSecure()]
                )?>" 
                method="get" id="form-userslist-filter"  name="formUserslistFilter" 
                    data-mage-init='{"validation":{}}'>
                    <table cellspacing="0" class="border wk-mp-list-table">
                        <thead>
                            <tr id="wk-mp-tr-heading">
                                <th><span><?= /* @noEscape */  __('Subscribed From') ?></span></th>
                                <th><span><?= /* @noEscape */  __('Subscribed Date') ?></span></th>
                                <th><span>&nbsp;</span></th>
                            </tr>
                        </thead>
                        <tbody class="wk-mp-body">
                            <tr>
                                <td>
                                    <span class="wk-mp-td-span">
                                    <input name="browser" id="user-browser" 
                                    class="input-text" value="<?php   /* @noEscape */
                                    if (isset($paramData['browser'])) { echo $paramData['browser']; } ?>" />
                                </span>
                                </td>
                                <td>
                                    <span class="wk-mp-td-span">
                                        <?= /* @noEscape */  __('From: ') ?>
                                        <input name="from_date" id="users-from-date" 
                                        class="input-text" 
                                        value="<?php /* @noEscape */
                                        if (isset($paramData['browser'])) { echo $paramData['from_date']; } ?>" />
                                    </span>                                
                                    <span class="wk-mp-td-span">
                                    <?= /* @noEscape */   __('To: ') ?>
                                        <input name="to_date" id="users-to-date" class="input-text" 
                                        value="<?php  /* @noEscape */
                                        if (isset($paramData['browser'])) { echo $paramData['to_date']; } ?>" />
                                    </span>
                                </td>
                                <td>
                                    <button class="button" title="Save" type="submit">
                                        <span><span><span><?= /* @noEscape */  __('Submit') ?></span></span></span>
                                    </button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </form>
            <?php if ($usersCollection && count($usersCollection)): ?>
                <?php $url=$block->getUrl($c_action, $secureurl);?>
                <form action="<?= /* @noEscape */$url; ?>" 
                method="post" id="form-userslist-massdelete" name="formUserslistMassdelete"
                         data-mage-init='{"validation":{}}'>
                        <?= /* @noEscape */  $block->getBlockHtml('formkey')?>
                        <?php if (count($templateCollection)) { ?>
                            <div class="wk-template-wrapper">
                                <select name='template' class="template">
                                    <option value=""><?= /* @noEscape */  __('-- select template --'); ?></option>
                                    <?php foreach ($templateCollection as $key => $template) { ?>
                                        <option value="<?= /* @noEscape */  $template->getId(); ?>">
                                        <?= /* @noEscape */  $template->getTitle(); ?></option>
                                        <?php
                                    } ?>
                                </select>
                                <button class="wk-button" 
                                title="<?= /* @noEscape */  __('Send Notification') ?>" 
                                type="submit"  id="send-notification">
                                    <span><span><?= /* @noEscape */  __('Send Notification') ?></span></span>
                                </button>
                            </div>
                        <?php } ?>

                        <table cellspacing="0" class="border wk-mp-list-table wk-mp-list-container-table">
                            <thead>
                                <tr class="wk-content">
                                    <th class="wk-check-first-td">
                                        <span>
                                            <input type="checkbox" name="mpselecctall" value="all" id="mpselecctall"/>
                                        </span>
                                    </th>
                                    <th class="wk-first-td">
                                        <span class="label name">
                                            <?= /* @noEscape */  __('Subscribed From')?>
                                        </span>
                                    </th>
                                    <th>
                                        <span class="label pro-status">
                                            <?= /* @noEscape */  __('Subscriber Name')?>
                                        </span>
                                    </th>
                                    <th class="wk-list-th-display">
                                        <span class="label">
                                            <?= /* @noEscape */  __('Subscribed At')?>
                                        </span>
                                    </th>                        
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 0;
                                foreach ($usersCollection as $token) {
                                    $i++;
                                    ?>
                                    <tr class="wk-row-view <?= /* @noEscape */
                                    $class = ($i == count($usersCollection))? 'wk-last_tr':''?>">
                                        <td class="wk-check-first-td">
                                            <span>
                                                <input type="checkbox" name="user_mass_delete[]" 
                                                class="mpcheckbox" value="<?= /* @noEscape */  $token->getId(); ?>"/>
                                            </span>
                                        </td>
                                        <td>        
                                            <span class="label">
                                                <?= /* @noEscape */  $token->getBrowser()?>
                                            </span>
                                        </td>
                                        <td>        
                                            <span class="label">
                                                <?= /* @noEscape */  $token->getName(); ?>
                                            </span>
                                        </td>
                                        <td>        
                                            <span class="label">
                                                <?= /* @noEscape */  $token->getCreatedAt()?>
                                            </span>
                                        </td>                        
                                    </tr>
                                    <?php
                                }?>
                            </tbody>
                        </table>
                    </form>                        
                <?php else: ?>
                    <div class="wk-emptymsg">
                        <?= /* @noEscape */  __('No Registered User(s) Available') ?>
                    </div>
                <?php endif ?>                    
            </div>
        </div>
        <?php if ($block->getPagerHtml()): ?>
            <div class="pushnotification-userslist-toolbar toolbar bottom">
            <?= /* @noEscape */  $block->getPagerHtml(); ?></div>
        <?php endif ?>
        <?php if ($usersCollection && is_array($usersCollection)):?>
        <h4>Subscribed <?= /* @noEscape */  "( ".count($usersCollection)." )";  ?></h4>
        <?php endif;?>
    </fieldset>    
    <div class="buttons-set">
        <p class="back-link">
            <a href="javascript:;" onclick="javascript: window.history.back();" class="left">
            &laquo; <?= /* @noEscape */  __('Back') ?></a>
        </p>
    </div>
</div>
<?php

    $releventData = [
        'sendNotificationUrl' => $block->getUrl(
            'mppushnotification/users/sendnotification',
            ['_secure' => $block->getRequest()->isSecure()]
        )
    ];

    $serializedData = $viewModel->getJsonHelper()->jsonEncode($releventData);

    ?>
<script type="text/x-magento-init">
    {
        "*": {
            "usersList": <?= /* @noEscape */  $serializedData; ?>
        }
    }
</script>