<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_CustomerSubaccount
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
/**
 * Merge Cart List
 *
 * @var \Webkul\CustomerSubaccount\Block\MergeCarts\Lists
 */

$subacccarts = $block->getCollection();
$helper = $block->getHelper();
?>
<form action="<?= /* @noEscape */ $block->getUrl('wkcs/mergeCarts/index')?>" method="get" id="form-cartlist-filter" name="formCartlistFilter" autocomplete="off" data-mage-init='{"validation": {}}'>
    <table cellspacing="0" class="wkcs-filter-table">
        <thead>
            <tr>
                <th><span><?= /* @noEscape */ __('Id')?></span></th>
                <th><span><?= /* @noEscape */ __('Customer Name')?></span></th>
                <th><span><?= /* @noEscape */ __('Customer Email')?></span></th>
                <th><span>&nbsp;</span></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <input type="text" class="input-text validate-greater-than-zero" name="qid" placeholder="<?= /* @noEscape */ __('Search by Id')?>" value="<?= /* @noEscape */ $block->getRequest()->getParam('qid')?>">
                </td>
                <td>
                    <input type="text" class="input-text validate-no-html-tags" name="qn" placeholder="<?= /* @noEscape */ __('Search by Name')?>" value="<?= /* @noEscape */ $block->getRequest()->getParam('qn')?>">
                </td>
                <td>
                    <input type="text" class="input-text validate-no-html-tags" name="qe" placeholder="<?= /* @noEscape */ __('Search by Email')?>" value="<?= /* @noEscape */ $block->getRequest()->getParam('qe')?>">
                </td>
                <td><button class="button" title="<?= /* @noEscape */ __('Save')?>" type="submit"><span><span><span><?= /* @noEscape */ __('Submit')?></span></span></span></button></td>
            </tr>
        </tbody>
    </table>
</form>
<?php if ($subacccarts && count($subacccarts)): ?>
    <div class="table-wrapper">
        <table class="data" id="subaccount-list">
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= /* @noEscape */ __('Id') ?></th>
                    <th scope="col" class="col customer-name"><?= /* @noEscape */ __('Customer Name') ?></th>
                    <th scope="col" class="col customer-email"><?= /* @noEscape */ __('Customer Email') ?></th>
                    <th scope="col" class="col itemqty"><?= /* @noEscape */ __('Items Qty') ?></th>
                    <th scope="col" class="col subtotal"><?= /* @noEscape */ __('Subtotal') ?></th>
                    <th scope="col" class="col view"><?= /* @noEscape */ __('Items') ?></th>
                    <th scope="col" style=" width: 115px; " class="col edit-action"><?= /* @noEscape */ __('Action') ?></th> 
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($subacccarts as $subacccarts):
                        $quote = $block->getQuote($subacccarts->getQuoteId());
                    ?>
                    <tr>
                        <td class="col id"><?= /* @noEscape */ $subacccarts->getId() ?></td>
                        <td class="col customer-name"><?= /* @noEscape */ $subacccarts->getName() ?></td>
                        <td class="col customer-email"><?= /* @noEscape */ $subacccarts->getEmail() ?></td>
                        <td class="col itemqty"><?= /* @noEscape */ $quote->getItemsCount() ?></td>
                        <td class="col subtotal"><?= /* @noEscape */ $block->getFormattedPrice($quote->getSubtotal()) ?></td>
                        <td class="col view">
                            <a href="<?= /* @noEscape */ $block->getUrl('wkcs/quote/index', ['id'=>$subacccarts->getQuoteId(), 'isAjax'=>1]) ?>"><?= /* @noEscape */ __('View') ?></a>
                        </td>
                        <td class="col action">
                            <a href="<?= /* @noEscape */ $block->getUrl('wkcs/mergeCarts/merge', ['id'=>$subacccarts->getQuoteId()]) ?>"><?= /* @noEscape */ __('Merge') ?></a>
                            <span class="wkcs-action-separator">|</span>
                            <a onclick="return confirm('<?= /* @noEscape */ __('Are you sure?')?>')" href="<?= /* @noEscape */ $block->getUrl('wkcs/mergeCarts/delete', ['id'=>$subacccarts->getQuoteId()]) ?>"><?= /* @noEscape */ __('Delete') ?></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="toolbar bottom"> <?= /* @noEscape */ $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span> <?= /* @noEscape */ __('No Cart available to Merge.'); ?></span></div>
<?php endif ?>

<script type="text/x-magento-init">
{
    "*" : {
        "mergecartlist": ""
    }
}
</script>