<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_CustomerSubaccount
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
/**
 * Request Approval
 *
 * @var $block \Webkul\CustomerSubaccount\Block\Checkout\Buttons
 */

if ($block->isCartApprovalRequired()) {
    ?>
<a href="<?= /* @noEscape */ $block->getUrl('wkcs/checkout/action', ['type'=>1]) ?>">
    <button type="button" title="<?= /* @noEscape */ __('Request Cart Approval')?>" class="action primary wkcs-cartpage-button">
        <span><?= /* @noEscape */ __('Request Cart Approval')?></span>
    </button>
</a>
    <?php
}
?>