<?php
/**
 * Webkul Software
 *
 * @category Webkul
 * @package Webkul_MpWalletSystem
 * @author Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license https://store.webkul.com/license.html
 */

$walletHelperBlock = $block->getLayout()->createBlock(\Webkul\MpWalletSystem\Block\Walletsystem::class);
$walletHelper = $walletHelperBlock->helper(\Webkul\MpWalletSystem\Helper\Data::class);
$walletBlock = $block->getLayout()->createBlock(\Webkul\MpWalletSystem\Block\Cart::class);
?>
<?php $mergedCells = ($walletHelperBlock->helper(\Magento\Tax\Helper\Data::class)->displayCartBothPrices() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<?php if (!$walletHelper->getCartStatus()) { ?>
        <div class="page-title title-buttons">
            <h2><?=$block->escapeHtml(__('Adding To Wallet'))?></h2>
        </div>
        <form action="<?=$block->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>"
              method="post"
              id="form-validate"
              data-mage-init='{"validation":{}}'
              class="form form-cart">
        <?=/*@noEscape*/ $block->getBlockHtml('formkey'); ?>
        <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : ''; ?>">
        <table id="shopping-cart-table" class="wk_ws_cart_table">
            <thead>
                <tr>
                    <th class="a-center"><span class="nobr">
                    <?=$block->escapeHtml(__("Wallet Holder's Name")) ?></span></th>
                    <th class="a-center"><span class="nobr"><?=$block->escapeHtml(__('Current Amount'))?></span>
                    </th>
                    <th class="a-center">
                        <?=$block->escapeHtml(__('Credited Amount')) ?>
                    </th>
                    <th class="a-center">
                        <?=$block->escapeHtml(__('Subtotal')) ?>
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody class='cart item'>
                <?php
                    $returnData = $walletHelper->getWalletDetailsData();
                foreach ($block->getItems() as $_item): ?>
                    <?php $productId = $_item->getProductId();
                    if ($productId==$returnData['walletProductId']) {?>
                        <tr class="item-info">
                            <?php
                            $currency_symbol = $returnData['currencySymbol'];
                            $currentWalletamount = $returnData['wallet_amount'];
                            ?>
                            <td class="a-center">
                            <?=$block->escapeHtml(__("%1's Wallet", $returnData['customer_name']));?></td>
                            <td class="a-center"><?=$block->escapeHtml($currency_symbol.$currentWalletamount);?></td>
                            <td class="a-center">
                            <?=$block->escapeHtml($currency_symbol.number_format($_item->getCustomPrice(), 2));?></td>
                            <td class="a-center">
                            <?=$block->escapeHtml($currency_symbol.($currentWalletamount + $_item->getCustomPrice()));?>
                            </td>
                        </tr>
                        <tr class='item-actions'>
                            <td colspan="100">
                                <div class='actions-toolbar'>
                                    <a href="#"
                                        title="<?=$block->escapeHtmlAttr(__('Remove item')); ?>"
                                        class="action action-delete wkProductDelete"
                                        url='<?=$block->escapeUrl($walletBlock->getDeletePostJson($_item))?>'>
                                        <span>
                                        <?=$block->escapeHtml(__('Remove item'))?>
                                        </span>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    <?php   }
                    ?>
                <?php endforeach ?>
                </tbody>

            </table>
    </div>
    </form>
<?php } else { ?>
<form action="<?=$block->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"validation":{}}'
          class="form form-cart">
    <?=/*@noEscape*/ $block->getBlockHtml('formkey'); ?>
    <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : ''; ?>">
        <table id="shopping-cart-table"
               class="cart items data table"
               data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <caption role="heading" aria-level="2" class="table-caption">
            <?=$block->escapeHtml(__('Shopping Cart Items'))?></caption>
            <thead>
                <tr>
                    <th class="col item" scope="col"><span><?=$block->escapeHtml(__('Item'))?></span></th>
                    <th class="col price" scope="col"><span><?=$block->escapeHtml(__('Price'))?></span></th>
                    <th class="col qty" scope="col"><span><?=$block->escapeHtml(__('Qty'))?></span></th>
                    <th class="col subtotal" scope="col"><span><?=$block->escapeHtml(__('Subtotal'))?></span></th>
                </tr>
            </thead>
            <?php foreach ($block->getItems() as $_item): ?>
                <?= $block->getItemHtml($_item) ?>
            <?php endforeach ?>
        </table>
    </div>
    <div class="cart main actions">
        <?php if ($block->getContinueShoppingUrl()): ?>
            <a class="action continue"
               href="<?= $block->escapeUrl(($block->getContinueShoppingUrl())) ?>"
               title="<?= $block->escapeHtml(__('Continue Shopping')); ?>">
                <span><?=$block->escapeHtml(__('Continue Shopping'))?></span>
            </a>
        <?php endif; ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-empty=""
                value="empty_cart"
                title="<?= $block->escapeHtml(__('Clear Shopping Cart')); ?>"
                class="action clear" id="empty_cart_button">
            <span><?=$block->escapeHtml(__('Clear Shopping Cart'))?></span>
        </button>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?= $block->escapeHtml(__('Update Shopping Cart')); ?>"
                class="action update">
            <span><?=$block->escapeHtml(__('Update Shopping Cart'))?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
    </div>
</form>
<?php }?>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after'); ?>
<?php
$formData = [
    'deletelink'    =>  '.wkProductDelete'
];
$serializedFormData = $walletHelperBlock->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($formData);
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Wkwalletsystem": <?=/*@noEscape*/$serializedFormData; ?>
        }
    }
</script>
