<?php
/**
 * Webkul Software
 *
 * @category  Webkul
 * @package   Webkul_Otp
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

/** @var $viewModel \Webkul\Otp\ViewModel\HelperViewModel */
$viewModel = $block->getViewModel();
$jsonHelper = $viewModel->helper(\Magento\Framework\Json\Helper\Data::class);
$otpHelper = $viewModel->helper(\Webkul\Otp\Helper\Data::class);

$otpModalConfig = $otpHelper->getOtpModalConfig();
$customerHelper = $viewModel->helper(\Webkul\Otp\Helper\Customer::class);
$usernameType = $customerHelper->getCurrentUsernameType();
$usernameFieldConfig = $customerHelper->getLoginUsernameFieldConfigByType($usernameType);

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<form class="form password forget"
      action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{
         "validation":{},
         "Webkul_Otp/js/login": <?= /** @noEscape */ $jsonHelper->jsonEncode($otpModalConfig) ?>
      }'>
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field note"><?= $block->escapeHtml($usernameFieldConfig['note']) ?></div>
        <div class="field email required">
            <label for="email_address" class="label">
                <span><?= $block->escapeHtml($usernameFieldConfig['label']) ?></span>
            </label>
            <div class="control">
                <input type="<?= $block->escapeHtmlAttr($usernameFieldConfig['type']) ?>"
                       name="email" alt="<?= $block->escapeHtmlAttr($usernameFieldConfig['alt']) ?>"
                       id="email_address" class="input-text"
                       value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>"
                       data-mage-init='{"mage/trim-input":{}}'
                       data-validate="<?= /** @noEscape */ $usernameFieldConfig['dataValidate'] ?>">
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary otpAuthElement">
                <span><?= $block->escapeHtml(__('Reset My Password')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>">
                <span><?= $block->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
