<?php
/**
 * Webkul Software.
 *
 * @category Webkul
 * @package Webkul_WebApplicationFirewall
 * @author Webkul
 * @copyright Copyright (c) WebkulSoftware Private Limited (https://webkul.com)
 * @license https://store.webkul.com/license.html
 *
 */

 //Block \Webkul\WebApplicationFirewall\Block\Adminhtml\DirectoryPermission
?>
<div class="page-main-actions">
    <div class="page-actions-inner">
        <div class="page-actions-buttons">
            <button type="button"
                    title="<?= $block->escapeHtml(__('Scan')); ?>"
                    class="action scalable primary">
                <span><?= $block->escapeHtml(__('Scan')) ?></span>
            </button>
        </div>
    </div>
</div>
