<?php 
/**
 * Webkul Software.
 *
 * @category Webkul
 * @package Webkul_WebApplicationFirewall
 * @author Webkul
 * @copyright Copyright (c) WebkulSoftware Private Limited (https://webkul.com)
 * @license https://store.webkul.com/license.html
 *
 */
// @codingStandardsIgnoreFile

?>

<script>
require(['prototype', 'Webkul_WebApplicationFirewall/js/device-uuid'], function(jQuery){
    let deviceIdField = '<input type="hidden" name="device_uuid" value="'+ new DeviceUUID().get() +'" />'
    $('login-form').insert(deviceIdField);
});
</script>


