<?php
/**
 * Webkul Software
 *
 * @category Webkul
 * @package Webkul_MpRewardSystem
 * @author Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license https://store.webkul.com/license.html
 */
/**
 * Manage rewardcart template
 *
 * @var $block \Webkul\MpRewardSystem\Block\Product\Index
 */
$helper = $block->getMarketplaceHelper();
$mpRewardHelper = $block->getRewardHelper();
$isPartner = $helper->isSeller();
$paramData = $block->getRequest()->getParams();
$filter = '';
$filterStatus = 2;
$filterPointsFrom = '';
$filterPointsTo = '';
if (isset($paramData['s'])) {
    $filter = $paramData['s'] != '' ? $paramData['s'] : '';
}
if (isset($paramData['status']) && $paramData['status'] != '') {
    $filterStatus = $paramData['status'] != '' ? $paramData['status'] : '';
}
if (isset($paramData['ponits_from'])) {
    $filterPointsFrom = $paramData['ponits_from'] != '' ? $paramData['ponits_from'] : '';
}
if (isset($paramData['ponits_to'])) {
    $filterPointsTo = $paramData['ponits_to'] != '' ? $paramData['ponits_to'] : '';
}
$_products_coll = $block->getAllProducts();
$enabledStatusText = __('Enabled');
$disabledStatusText = __('Disabled');
if ($isPartner == 1):
    ?>
 <div class="wk-mp-design">
     <fieldset class="fieldset info wk-mp-fieldset">
         <div class="grid">
             <div class="hor-scroll">
                 <form action="<?=$block->escapeUrl($block
                    ->getUrl('mprewardsystem/product/index', ['_secure' => $block->getRequest()->isSecure()]))?>" 
                 method="get" id="form-productlist-filter"  name="formProductlistFilter" 
                 data-mage-init='{"validation":{}}'>
                     <table cellspacing="0" class="border wk-mp-list-table">
                         <thead>
                             <tr id="wk-mp-tr-heading">
                                 <th><span><?=/* @noEscape */__('Product Name')?></span></th>
                                 <th><span><?=/* @noEscape */__('Reward Points')?></span></th>
                                 <th><span><?=/* @noEscape */__('Reward Status')?></span></th>
                                 <th><span>&nbsp;</span></th>
                             </tr>
                         </thead>
                         <tbody class="wk-mp-body" id="colender-check">
                             <tr>
                                 <td>
                                     <input type="text" class="input-text" name="s" 
                                     placeholder='<?=/* @noEscape */__('Search by product name')?>' 
                                     value="<?=$block->escapeHtml($filter)?>"/>
                                 </td>
                                 <td>
                                     <span class="wk-mp-td-span">
                                         <?=/* @noEscape */__('From: ')?>
                                         <input name="ponits_from" id="ponits_from" class="input-text" 
                                         value="<?=$block->escapeHtml($filterPointsFrom)?>" />
                                     </span>
                                     <span class="wk-mp-td-span">
                                         <?=/* @noEscape */__('To: ')?>
                                         <input name="ponits_to" id="ponits_to" class="input-text" 
                                         value="<?=$block->escapeHtml($filterPointsTo)?>" />
                                     </span>
                                 </td>
                                 <td>
                                     <select name="status" class="input-text">
                                         <option value=""><?=/* @noEscape */__('All')?></option>
                                         <option value="1" <?php if ($filterStatus == 1) {
                                                echo 'selected="selected"';
                                                           }
                                                            ?>>
                                             <?=$block->escapeHtml($enabledStatusText)?>
                                         </option>
                                         <option value="0" <?php if ($filterStatus == 0) {
                                                echo 'selected="selected"';
                                                           }
                                                            ?>>
                                             <?=$block->escapeHtml($disabledStatusText)?>
                                         </option>
                                     </select>
                                 </td>
                                 <td>
                                     <button class="button" title="Save" type="submit">
                                         <span><span><span><?=/* @noEscape */__('Submit')?></span></span></span>
                                     </button>
                                 </td>
                             </tr>
                         </tbody>
                     </table>
                 </form>
                 <div data-bind="scope: 'product-list-component'">
                 <?php if ($_products_coll && $_products_coll->getSize()): ?>
                     <form action="<?=$block->escapeUrl($block
                        ->getUrl('mprewardsystem/product/massAssign', ['_secure' => $block
                        ->getRequest()->isSecure()]))?>" method="post" id="form-productlist-massassign" 
                        dname="formProductlistMassdelete" data-mage-init='{"validation":{}}'>
                         <?=$block->getBlockHtml('formkey')?>
                         <?=$block->getBlockHtml('seller.formkey')?>
                         <div class="field">
                                    <label class="label" for="rewardpoint">
                                        <span><?=/* @noEscape */__('Enter Points')?></span>
                                    </label>
                                    <div class="control">
                                        <input id="rewardpoint" name="rewardpoint" type="text" class="input-text" />
                                    </div>
                                    <div class="sampleData">
                                       <input id="checkedData" name="checkedData" type="hidden" class="input-text" />
                                     </div>
                                </div>
                        <div class="field">
                                    <label class="label" for="status">
                                        <span style="width:140px"><?=/* @noEscape */__('Reward Point Status')?></span>
                                    </label>
                                    <div class="control">
                                        <select id="status" name="status" type="text" class="input-text required-entry">
                                        <option value=0 selected="selected"><?=/* @noEscape */__('Disable')?></option>
                                        <option value=1><?=/* @noEscape */__('Enable')?></option>
                                        </select>
                                    </div>
                                </div>
                         <button class="button" title="<?=/* @noEscape */__('Assign Rewards')?>" 
                         type="submit" style="float: left;padding: 5px;"  id="mass-assign-butn">
                             <span><span><?=/* @noEscape */__('Assign Rewards')?></span></span>
                         </button>
                             <!-- ko template: getTemplate() --><!-- /ko -->
                         <table cellspacing="0" class="border wk-mp-list-table wk-mp-list-container-table">
                             <thead>
                                 <tr class="wk-content">
                                     <th class="wk-check-first-td">
                                         <span>
                                             <input type="checkbox" name="mpselecctall" value="all" id="mpselecctall" 
                                             autocomplete="off"/>
                                         </span>
                                     </th>
                                     <th class="wk-first-td">
                                         <span class="label name">
                                             <?=/* @noEscape */__('Product')?>
                                         </span>
                                     </th>
                                     <th>
                                         <span class="label pro-status">
                                             <?=/* @noEscape */__('Type')?>
                                         </span>
                                     </th>
                                     <th>
                                         <span class="label pro-status">
                                             <?=/* @noEscape */__('Reward Points')?>
                                         </span>
                                     </th>
                                     <th>
                                         <span class="label pro-status">
                                             <?=/* @noEscape */__('Reward Status')?>
                                         </span>
                                     </th>
                                 </tr>
                             </thead>
                             <tbody>
                                 <?php
                                    $i = 0;
                                    foreach ($block->getAllProducts() as $products) {
                                        $product = $block->getProductData($products->getMageproductId());
                                        $i++;
                                        $rewardStatus = "";
                                        if ($products->getRewardStatus() != '') {
                                            $rewardStatus = $products->getRewardStatus() ? "Enable" : "Disable";
                                        }
                                        ?>
                                     <tr class="wk-row-view <?=$class = ($i == $block
                                         ->getAllProducts()->getSize()) ? 'wk-last_tr' : ''?>">
                                         <td class="wk-check-first-td">
                                             <span>
                                                 <input type="checkbox" name="reward_mass_assign[]" autocomplete="off" 
                                                 class="mpcheckbox" 
                                                 value="<?=$block->escapeHtml($products->getMageproductId());?>"/>
                                             </span>
                                         </td>
                                         <td class="wk-first_td">
                                             <input type="hidden" class="hidden-id" 
                                             value="<?=$block->escapeHtml($products->getMageproductId());?>" />
                                             <div class="label name" 
                                             title="<?=$block->escapeHtml($product->getName());?>">
                                                 <div class="wk-pro-divide2">
                                                     <div style="width:100%;">
                                                         <?php if ($product->getStatus() == 1
                                                            && $product->getVisibility() != 1) {?>
                                                             <a href="<?=$block
                                                                ->escapeUrl($product->getProductUrl())?>" 
                                                             target="blank">
                                                            <?php }?>
                                                             <?=$block->escapeHtml($product->getName());?>
                                                         <?php if ($product->getStatus() == 1
                                                             && $product->getVisibility() != 1) {?>
                                                             </a>
                                                            <?php }?>
                                                     </div>
                                                     <div style="width:100%;float:left;">
                                                         <?php
                                                            if ($product->getPrice() * 1) {
                                                                echo $block->escapeHtml($block
                                                                ->getFormatedPrice($product
                                                                ->getPrice(), $helper->getCurrencySymbol()));
                                                            } else {
                                                                echo $block->escapeHtml($helper
                                                                ->getCurrencySymbol() . '0.00');
                                                            }
                                                            ?>
                                                     </div>
                                                 </div>
                                             </div>
                                         </td>
                                         <td>
                                             <span class="label pro-status">
                                                 <?=$block->escapeHtml($product->getTypeId())?>
                                             </span>
                                         </td>
                                         <td>
                                             <span class="label pro-status">
                                                 <?=$block->escapeHtml($products->getPoints())?>
                                             </span>
                                         </td>
                                         <td>
                                             <span class="label pro-status">
                                                 <?=$block->escapeHtml($rewardStatus)?>
                                             </span>
                                         </td>
                                     </tr>
                                        <?php
                                    }?>
                             </tbody>
                         </table>
                     </form>
                     </div>
                    <?php else: ?>
                     <div class="wk-emptymsg">
                         <?=/* @noEscape */__('No Product Available')?>
                     </div>
                    <?php endif?>
             </div>
         </div>
         <?php if ($block->getPagerHtml()): ?>
             <div class="order-products-toolbar toolbar bottom"><?=$block->getPagerHtml();?></div>
            <?php endif?>
     </fieldset>
     <div class="buttons-set">
         <p class="back-link">
             <a href="javascript:;" onclick="javascript: window.history.back();" 
             class="left">&laquo; <?=/* @noEscape */__('Back')?></a>
         </p>
     </div>
 </div>
<?php endif;?>
<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "product-list-component": {
                            "component": "rewardProductList",
                            "template" : "Webkul_MpRewardSystem/product-list"
                        }
                    }
                }
            }
        }
</script>
