<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpWholesale
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

/** @var \Magento\Catalog\Block\Adminhtml\Category\AssignProducts $block */

/** @var \Magento\Catalog\Block\Adminhtml\Category\Tab\Product $blockGrid */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= /* @noEscape */ $block->getGridHtml(); ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Webkul_MpWholesale/js/product/assign-products": {
                "selectedProducts": <?=  /* @noEscape */ $block->getWholeSalerAssignedProductJson(); ?>,
                "gridJsObjectName": <?=  /* @noEscape */ '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
<input type="hidden" name="products_id" id="in_adminassign_products" 
class="required-entry" data-form-part="wholesale_product_form" value="" />
