<?php
/**
 * Webkul_MpAuction product view page block template.
 * @category  Webkul
 * @package   Webkul_MpAuction
 * @author    Webkul
 * @copyright Copyright (c)  Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$mpAuctionViewModel = $block->getMpAuctionViewmodel();
$auctionData = $block->getAuctionDetail();
$aucConfig = $block->getAuctionConfiguration();
$serializedAuctionData = $mpAuctionViewModel->getJsonHelper()->jsonEncode($auctionData);
if (count($auctionData) > 0
&& isset($auctionData['new_auction_start']) && !$auctionData['new_auction_start']) {
    if ($auctionData['current_time_stamp'] >= $auctionData['start_auction_time_stamp']
        && $auctionData['current_time_stamp'] <= $auctionData['stop_auction_time_stamp']) {
        $difference= $auctionData['stop_auction_time_stamp'] - $auctionData['current_time_stamp'];
        ?>
        <div class="wk_product_background <?= (isset($auctionData['pro_buy_it_now']) && $auctionData['pro_buy_it_now'] ? 'wk-buy-it-now': '')?>" data-mpauction-blockid="mpauaction-1">
            <div class="product-collateral">
                <div class="box-collateral box-tags">
                <?php if ($difference > 0) { ?>
                    <div id='bottom_lin'>
                        <div class='bid_title'><?= /* @noEscape */ $auctionData['auction_title'] ?></div>
                        <div class="auction-timer-block">
                            <div class="wk-auction-timer-div">
                                <div class="wk-auction-clock-main-div">
                                    <div class="auction-bid-timer"><?= /* @noEscape */ __('Ends in') ?></div>
                                    <p class="wk_front_dd_countdownnew" id="wk_front_dd_note" data-diff-timestamp ="<?= /* @noEscape */ $difference;?>"></p>
                                </div>
                                <?php if ($aucConfig['show_curt_auc_price']) { ?>
                                <div class="wk-auction-current-bid">
                                    <div class="auction-bid-timer"><?= /* @noEscape */ __('Current Bid Amount') ?></div>
                                    <div class="wk-auction-clock-span"> <?= /* @noEscape */ $block->formatPrice($auctionData['current_auction_amount']) ;?></div>
                                    <?php if ($aucConfig['show_auc_detail']) { ?>
                                        <div class="bid_link">
                                            <a href="#normal-bid-record" class='wk-auction-view-bid-link anchr'>
                                                <?= /* @noEscape */ $block->getNumberOfBid($auctionData['entity_id']); ?>
                                            </a>
                                        </div>
                                    <?php } ?>
                                </div>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                        <div class="wk-auction-bid-details">
                        <?php if ($aucConfig['show_auc_detail']) { ?>
                            <div class="auction-bid-first-column">
                                <div class="wk_row">
                                    <label ><?= /* @noEscape */ __('Minimum Qty:') ?></label>
                                    <span class='value'><?= /* @noEscape */ $auctionData['min_qty']; ?></span>
                                </div>
                                <div class="wk_row">
                                    <label ><?= /* @noEscape */ __('Open Bid Amount:') ?></label>
                                    <span class='value'><?= /* @noEscape */ $block->formatPrice($auctionData['starting_price']) ;?></span>
                                </div>
                            </div>
                        <?php } ?>
                            <div class="auction-bid-second-column">
                            <?php if ($aucConfig['show_auc_detail']) { ?>
                                <div class="wk_row">
                                    <label ><?= /* @noEscape */ __('Maximum Qty:') ?></label>
                                    <span class='value'><?= /* @noEscape */ $auctionData['max_qty']; ?></span>
                                </div>
                            <?php } ?>
                                <?php if ($aucConfig['show_curt_auc_price']) { ?>
                                    <div class="wk_row">
                                        <label ><?= /* @noEscape */ __('Next Minimum Bid Amount:') ?></label>
                                        <span class='value'><?= /* @noEscape */ $block->formatPrice($auctionData['min_amount'] + 0.01) ;?></span>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                    <div class="form-add">
                        <div class="wk_wrap">
                            <form action="<?= /* @noEscape */ $block->getAuctionFormAction() ?>" enctype="multipart/form-data" method="post" class="mp_bidding_form" id="form-biddings-amount">
                                <input type="hidden" name="entity_id" value="<?= /* @noEscape */ $auctionData['entity_id']; ?>" />
                                <input type="hidden" name="product_id" value="<?= /* @noEscape */ $auctionData['product_id']; ?>" />
                                <input type="hidden" name="pro_name" value="<?= /* @noEscape */ $auctionData['pro_name']; ?>" />
                                <input type="hidden" name="auto_auction_opt" value="<?= /* @noEscape */ $auctionData['auto_auction_opt']; ?>" />
                                <input type="hidden" name="pro_url" value="<?= /* @noEscape */ $auctionData['pro_url']; ?>" />
                                <input type="hidden" name="stop_auction_time_stamp" value="<?= /* @noEscape */ $auctionData['stop_auction_time_stamp']; ?>">
                                <div class="input-box">
                                    <input type="text" name="bidding_amount" id="bidding_amount" class="input-text required-entry mpbidding_amount" placeholder="<?= /* @noEscape */  __('Enter Bid Amount'); ?>" required="required" oncut="return false;" oncopy="return false;" onpaste="return false;"/>
                                    <button class="action primary" id='target' title="<?= /* @noEscape */ __('Bidding') ?>" type="submit" >
                                        <span><?= /* @noEscape */ __('Bid Now') ?></span>
                                    </button>
                                    <div class="input-box auto-bid" >
                                        <?php if ($aucConfig['auto_enable'] && $auctionData['auto_auction_opt']) { ?>
                                            <input type="checkbox" value="1" name="auto_bid_allowed" id="auto_bid_allowed"/>
                                            <span><?= /* @noEscape */ __('Place Bid as Automatic') ?></span>
                                        <?php } ?>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                <?php } ?>
                </div>
            </div>
        </div>
        <?php
    } elseif ($auctionData['current_time_stamp'] < $auctionData['start_auction_time_stamp']) {
        $difference= $auctionData['start_auction_time_stamp'] - $auctionData['current_time_stamp'];
        ?>
        <div class="wk_product_background" data-mpauction-blockid="mpauaction-2">
            <div class="product-collateral">
                <div class="box-collateral box-tags">
                <?php if ($difference > 0) { ?>
                    <div id='bottom_lin'>
                        <div class='bid_title'><?= /* @noEscape */ $auctionData['auction_title'] ?></div>
                        <div class="auction-timer-block">
                            <div class="wk-auction-timer-div">
                                <div class="wk-auction-clock-main-div">
                                    <div class="auction-bid-timer"><?= /* @noEscape */ __('Start in') ?></div>
                                    <p class="wk_front_dd_countdownnew" id="wk_front_dd_note" data-diff-timestamp ="<?= /* @noEscape */ $difference;?>"></p>
                                </div>
                                <?php if ($aucConfig['show_curt_auc_price']) { ?>
                                <div class="wk-auction-current-bid">
                                    <div class="auction-bid-timer"><?= /* @noEscape */ __('Current Bid Amount') ?></div>
                                    <div class="wk-auction-clock-span"> <?= /* @noEscape */ $block->formatPrice($auctionData['current_auction_amount']) ;?></div>
                                    <?php if ($aucConfig['show_auc_detail']) { ?>
                                        <div class="bid_link">
                                            <a href="#normal-bid-record" class='wk-auction-view-bid-link anchr'>
                                                <?= /* @noEscape */ $block->getNumberOfBid($auctionData['entity_id']); ?>
                                            </a>
                                        </div>
                                    <?php } ?>
                                </div>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                        <div class="wk-auction-bid-details">
                        <?php if ($aucConfig['show_auc_detail']) { ?>
                            <div class="auction-bid-first-column">
                                <div class="wk_row">
                                    <label ><?= /* @noEscape */ __('Minimum Qty:') ?></label>
                                    <span class='value'><?= /* @noEscape */ $auctionData['min_qty']; ?></span>
                                </div>
                                <div class="wk_row">
                                    <label ><?= /* @noEscape */ __('Open Bid Amount:') ?></label>
                                    <span class='value'><?= /* @noEscape */ $block->formatPrice($auctionData['starting_price']) ;?></span>
                                </div>
                            </div>
                        <?php } ?>
                            <div class="auction-bid-second-column">
                            <?php if ($aucConfig['show_auc_detail']) { ?>
                                <div class="wk_row">
                                    <label ><?= /* @noEscape */ __('Maximum Qty:') ?></label>
                                    <span class='value'><?= /* @noEscape */ $auctionData['max_qty']; ?></span>
                                </div>
                            <?php } ?>
                                <?php if ($aucConfig['show_curt_auc_price']) { ?>
                                    <div class="wk_row">
                                        <label ><?= /* @noEscape */ __('Next Minimum Bid Amount:') ?></label>
                                        <span class='value'><?= /* @noEscape */ $block->formatPrice($auctionData['min_amount'] + 0.01) ;?></span>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                    <div class="form-add">
                        <div class="wk_wrap">
                            
                        </div>
                    </div>
                <?php } ?>
                </div>
            </div>
        </div>
        <?php
    //To Do
        $timezone="";
    } elseif ($auctionData['current_time_stamp'] >= $auctionData['stop_auction_time_stamp']) {
        $aftComp = $block->getAuctionDetailAftetEnd($auctionData);
        if ($aftComp['watting_user']) { ?>
            <div class="wk_product_background" data-mpauction-blockid="mpauaction-3"> 
                <div class="product-collateral"> 
                    <div class="box-collateral box-tags wk_row"> 
                        <?php if ($aucConfig['show_auc_detail']) { ?>
                        <div class='bid_link'>
                            <span>
                                <a href="#normal-bid-record" class='anchr wk-auction-view-bid-link'>
                                    <?= /* @noEscape */ $block->getNumberOfBid($auctionData['entity_id']); ?>
                                </a>
                            </span>
                        </div>
                    <?php } ?>
                        <h3><?= /* @noEscape */ $aftComp['watting_user']['msg_lable']; ?></h3>
                    </div>
                </div>
            </div>
        <?php } elseif ($aftComp['winner'] && $aftComp['winner']['price']) {
                $winner = $aftComp['winner'];
            if ($winner['time_for_buy'] > 0) {
                if ($winner['shop'] == 0) { ?>
                        <div id="winner-data-container" class="wk_product_background allow-for-buy" data-cart-label="<?= /* @noEscape */ __('Buy with ') . $block->formatPrice($winner['price']) ?>" data-mpauction-blockid="mpauaction-4"> 
                            <div class="product-collateral">
                                <div id='bottom_lin' class="box-collateral box-tags wk_row">
                                    <div class='bid_title'><?php  ?></div>
                                    <div class="auction-timer-block">
                                        <div class="wk-auction-timer-div">
                                            <div class="wk-auction-clock-main-div">
                                                <div class="auction-bid-timer"><?= /* @noEscape */ __('Time remaining to buy') ?></div>
                                                <p class="wk_front_dd_countdownnew" id="wk_front_dd_note" data-diff-timestamp ="<?= /* @noEscape */ $winner['time_for_buy'];?>"></p>
                                            </div>
                                            <div class="wk-auction-current-bid">
                                                <div class="auction-bid-timer"><?= /* @noEscape */ __("Your's Bid Amount") ?></div>
                                                <div class="wk-auction-clock-span"> <?= /* @noEscape */ $block->formatPrice($auctionData['current_auction_amount']) ;?></div>
                                                <?php if ($aucConfig['show_auc_detail']) { ?>
                                                    <div class="bid_link">
                                                        <a href="#normal-bid-record" class='wk-auction-view-bid-link anchr'>
                                                            <?= /* @noEscape */ $block->getNumberOfBid($auctionData['entity_id']); ?>
                                                        </a>
                                                    </div>
                                                <?php } ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="wk-auction-bid-details">
                                    <div class="auction-bid-first-column">
                                        <div class="wk_row">
                                            <label ><?= /* @noEscape */ __('Minimum Qty:') ?></label>
                                            <span class='value'><?= /* @noEscape */ $auctionData['min_qty']; ?></span>
                                        </div>
                                        <div class="wk_row">
                                            <label ><?= /* @noEscape */ __('Open Bid Amount:') ?></label>
                                            <span class='value'><?= /* @noEscape */ $block->formatPrice($auctionData['starting_price']) ;?></span>
                                        </div>
                                    </div>
                                    <div class="auction-bid-second-column">
                                        <div class="wk_row">
                                            <label ><?= /* @noEscape */ __('Maximum Qty:') ?></label>
                                            <span class='value'><?= /* @noEscape */ $auctionData['max_qty']; ?></span>
                                        </div>
                                        <div class="wk_row auction-winner-message">
                                                <?= /* @noEscape */ __($aucConfig['show_winner_msg'].' Now, you can get it in '.$block->formatPrice($winner['price'])) ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php } else { ?>
                    <div class="wk_product_background" data-mpauction-blockid="mpauaction-5">
                        <div id="bottom_lin">
                            <div class='bid_title'><?= /* @noEscape */ $auctionData['auction_title'] ?></div>
                            <div class="wk_row">
                                <?= /* @noEscape */ __('You have already bought this product.');?>
                            </div>
                        </div>
                    </div>
                    <?php }
            }
        } else { ?>
                <div class="wk_product_background" data-mpauction-blockid="mpauaction-6"> 
                    <div class="product-collateral"> 
                        <div class="box-collateral box-tags wk_row"> 
                        <?php if ($aucConfig['show_auc_detail']) { ?>
                            <div class='bid_link'>
                                <span>
                                    <a href="#normal-bid-record" class='anchr wk-auction-view-bid-link'>
                                        <?= /* @noEscape */ $block->getNumberOfBid($auctionData['entity_id']); ?>
                                    </a>
                                </span>
                            </div>
                        <?php } ?>
                            <h3><?= /* @noEscape */ __('Auction time has been ended.'); ?></h3>
                        </div>
                    </div>
                </div>
        <?php   }
    } ?>
    <?php
} else { ?>
<style>
.product-add-form {
    display: block;
}
</style>
<?php }
if (count($auctionData) > 0) { ?>
    <script type="text/x-magento-init">
        {
            "body": {
                "Webkul_MpAuction/js/viewonproduct":
                {
                    "buyItNow": "<?= /* @noEscape */ __('Buy it now')?>",
                    "auctionData" : <?= /* @noEscape */ $serializedAuctionData?>,
                    "auctionType" : "<?= /* @noEscape */ $block->getProAuctionType()?>",
                    "cacheFlush"  : "<?= /* @noEscape */ $block->getUrl('mpauction/account/product');?>"
                }
            }
        }
    </script>
<?php }
?>
<style>
 .wk-auction-clock-label-hr span, 
    .wk-auction-clock-label-mi span, 
    .wk-auction-clock-label-sec span,
    .wk-auction-clock-label-dd span {
    white-space: nowrap;     
    overflow: hidden; 
    text-overflow: ellipsis; 
    width: 58px; 
    display: inline-block;
}
.wk-auction-clock-label-hr span:hover, 
    .wk-auction-clock-label-mi span:hover, 
    .wk-auction-clock-label-sec span:hover,
    .wk-auction-clock-label-dd span:hover {
    overflow: visible; 
    white-space: normal; 
    width: auto;
    position: relative;
    background-color:#FFF;
}
.limiter {
    float: right;
}
.order-products-toolbar, .customer-addresses-toolbar {
    position: relative;
    margin-top: 11px;
}
</style>
