<!-- /**
* Webkul Software.
*
* @category  Webkul
* @package   Webkul_MarketplaceProductLabels
* @author    Webkul
* @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
* @license   https://store.webkul.com/license.html
*/  -->
<?php
    $mpSellerProfifle = $block->getLayout()->createBlock(\Webkul\Marketplace\Block\Profile::class);
    $product = [];
    $productCollection = $mpSellerProfifle->getBestsellProducts();
    $count = 0;

foreach ($productCollection as $_product) {
    if ($_product['entity_id']) {
        $product[$count] = $_product['entity_id'];
        $count++;
    }
}
    $encodedJsData = $block->getJsonEncode($product);
?>

<script type="text/x-magento-init">
    {
        "*":{
            "Webkul_MarketplaceProductLabels/js/sellerProfileJs":{
                "imageTag": {
                  
                  "url": "<?= /* @noEscape */ $block->getUrl('mplabels/check/checksearch') ; ?>",
                  "base":"<?= /* @noEscape */ $block->getBaseUrl().'mplabel/label/' ; ?>",
                  "productCollection": <?= /* @noEscape */ $encodedJsData; ?>
                }
            }
        }
    }
</script>