<!-- 
/**
 * @category   Webkul
 * @package    Webkul_MpPushNotification
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */  -->

<?php
// $viewModel = $block->getViewModel();
// $helper = $viewModel->getHelper();
// $data = [
//     "apiKey"=>$helper->getServerKey(),
//     'swPath' => $block->getViewFileUrl('Webkul_MpPushNotification::js/service-worker-script.js'),
//     'ajaxUrl' => $block->getUrl('mppushnotification/users/save')
// ];

// $serializedData = $viewModel->getJsonHelper()->jsonEncode($data);

?>

