<!--
/**
 * Webkul Software
 *
 * @category Webkul
 * @package Webkul_MpWalletSystem
 * @author Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license https://store.webkul.com/license.html
 */
-->
<?php
$walletBlock = $block->getLayout()->createBlock(\Webkul\MpWalletSystem\Block\Walletsystem::class);
?>
<div class="entry-edit">
    <div id="wallet_add_block">
        <form action="
        <?= $block->escapeUrl($block->getUrl('mpwalletsystem/wallet/massaddamount')) ?>
        " enctype="multipart/form-data" method="post" id="formmassadd">
            <?=/*@noEscape*/ $block->getBlockHtml('formkey')?>
            <input type="hidden" name="wkcustomerids" id="wkcustomerids" value="" />
            <fieldset class="fieldset admin__fieldset">
                <legend class="legend">
                    <span><?=$block->escapeHtml(__('Adjust amount to wallet')) ?></span>
                </legend>
                <div class="messages"></div>
                <div class="field admin__field">
                    <label class="label" for="walletamount">
                        <span><?=$block->escapeHtml(__('Enter Amount'))?></span>
                    </label>
                    <div class="control">
                        <input id="walletamount" name="walletamount" type="text" class="input-text required-entry" />
                    </div>
                </div>
                <div class="field admin__field">
                    <label class="label" for="walletactiontype">
                        <span><?=$block->escapeHtml(__('Action want to perform on amount'))?></span>
                    </label>
                    <div class="control">
                        <select id="walletactiontype" name="walletactiontype" 
                        type="text" class="input-text required-entry" style="margin-left:0 !important">
                            <option value="credit" selected="selected">
                            <?=$block->escapeHtml(__('Credit Amount'))?></option>
                            <option value="debit"><?=$block->escapeHtml(__('Debit Amount'))?></option>
                        </select>
                    </div>
                </div>
                <div class="field admin__field">
                    <label class="label" for="walletnote">
                        <span><?=$block->escapeHtml(__('Note for the transaction'))?></span>
                    </label>
                    <div class="control">
                        <textarea id="walletnote" name="walletnote" class="input-text walletnote"></textarea>
                    </div>
                </div>
                <button title="<?=$block->escapeHtmlAttr(__('Update amount to wallet')) ?>" 
                type="button" id="save_butn">
                <span><span><span>
                <?= $block->escapeHtml(__('Update amount'))?></span></span></span></button>
            </fieldset>
        </form>
    </div>

    <div class="ask_data popover_background" id="ask_data">
        <div id="wk-mp-ask-data">
                <div tabindex="0"
                    data-type="popup"
                    data-role="modal"
                    class="modal-popup modal-slide _inner-scroll wk-mp-model-popup _show"
                >
                    <div tabindex="0" data-role="focusable-start"></div>
                    <div data-role="focusable-scope" class="modal-inner-wrap">
                        <header class="modal-header">
                            <h4 class="modal-title"><?=$block->escapeHtml(__('Adjust Amount')) ?></h4>
                            <button type="button"
                                data-role="closeBtn"
                                class="popover_close action-close wk_close"
                            >
                                <span>Close</span>
                            </button>
                            <span  class="wk-clear" ></span>
                        </header>
                        <form id="walletform" method="get" enctype="multipart/form-data" 
                        action="<?=$block->escapeUrl($block->getUrl('mpwalletsystem/wallet/singleaddamount/'))?>">
                            <?=/*@noEscape*/ $block->getBlockHtml('formkey')?>

                            <div class="modal-body form-list field required">
                                <input type="hidden"
                                    name="customerid"
                                    id="customerid"
                                    value=""
                                />
                                <label class="label"><?=$block->escapeHtml(__("Amount")); ?> :</label>
                                <input type="text"
                                    class="queryquestion wk-contact_input_fields required-entry 
                                    validate-greater-than-zero walletamount"
                                    name="walletamount"
                                />
                                <label class="label">
                                    <?=$block->escapeHtml(__("Action perform on amount")); ?> :
                                </label>
                                <select id="walletactiontype" name="walletactiontype" type="text" 
                                class="wk-contact_input_fields required-entry">
                                    <option value="credit" selected="selected">
                                    <?=$block->escapeHtml(__('Credit Amount'))?>
                                    </option>
                                    <option value="debit"><?=$block->escapeHtml(__('Debit Amount'))?></option>
                                </select>
                                <label class="label"><?=$block->escapeHtml(__("Transaction Note")); ?> :</label>
                                <textarea
                                    class="queryquestion wk-contact_input_fields required-entry walletnote"
                                    name="walletnote"
                                    style="width:100%;"
                                ></textarea>
                            </div>
                            <div class="modal-footer">
                                <span class="error"></span>
                                <span class="errormail"></span>
                                <input type="button"
                                    value="<?=$block->escapeHtmlAttr(__('Submit')) ?>"
                                    id="save_butn"
                                    class="submit_button clickask action-primary"
                                />
                                <input type="reset"
                                    value="<?=$block->escapeHtmlAttr(__('Reset')) ?>"
                                    id="resetbtn"
                                    class="action-primary"
                                />
                                <span class="wk-clear"></span>
                            </div>
                        </form>
                    </div>
                    <div tabindex="0" data-role="focusable-end"></div>
                </div>
            <!-- </div> -->
        </div>
    </div>
</div>
<?= $block->getGridHtml(); ?>
<?php
    $blockGrid = $block->getBlockGrid();
    $gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getChildHtml('grid') ?>
<?php
$formData = [
    'wkcustomerid'    =>    '#wkcustomerids',
    'savebtn'    =>    '#save_butn',
    'massupdateform'    => '#formmassadd',
    'askdata'    =>    '#ask_data',
    'submitButton'    =>    '.submit_button',
    'walletform'    =>    '#walletform'
];
$serializedFormData = $walletBlock->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($formData);
?>
<script type="text/x-magento-init">
    {
        "*": {
            "WkWalletsystem": <?=/*@noEscape*/  $serializedFormData; ?>
        }
    }
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Webkul_MpWalletSystem/js/assign-customer": {
                "gridJsObjectName": <?=/*@noEscape*/ '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
