<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_CustomerSubaccount
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
/**
 * Product View Page
 *
 * @var \Webkul\CustomerSubaccount\Block\Catalog\Product
 */
?>
<?php
if ($block->shouldRemoveReview()) { ?>
    <script type="text/x-magento-init">
    {
        "*" : {
            "reviewProduct": ""
        }
    }
    </script>
<?php } ?>