<!-- /**
* Webkul Software.
*
* @category  Webkul
* @package   Webkul_MarketplaceProductLabels
* @author    Webkul
* @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
* @license   https://store.webkul.com/license.html
*/  -->
<script type="text/x-magento-init">
    {
        "*":{
            "Webkul_MarketplaceProductLabels/js/showLabelJS":{
                "imageTag": {
                  
                  "url": "<?= /* @noEscape */ $block->getUrl('mplabels/check/checksearch') ; ?>",
                  "base":"<?= /* @noEscape */ $block->getBaseUrl().'mplabel/label/' ; ?>"
                }
            }
        }
    }
</script>