<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MarketplaceProductLabels
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

$_helper = $block->getHelperObject();
$allowedImgExtensions = $_helper->getConfigData('allowed_image_extensions');
$labelId = $block->getRequest()->getParam('id');
$labeldata = $block->getLabelData($labelId)->getData();
$labelStatus = $labeldata[0]['status'];
$imageSrc = $labeldata[0]['image_name'];
if ($labelStatus == 0) {
    $statusYes = '';
}
$position = [
    \Webkul\MarketplaceProductLabels\Model\Label::POSITION_TOP_LEFT =>__('Top-Left'),
    \Webkul\MarketplaceProductLabels\Model\Label::POSITION_TOP_RIGHT =>__('Top-Right'),
    \Webkul\MarketplaceProductLabels\Model\Label::POSITION_BOTTOM_LEFT => __('Bottom-Left'),
    \Webkul\MarketplaceProductLabels\Model\Label::POSITION_BOTTOM_RIGHT => __('Bottom-Right')
];
$imageSrc = $block->getMediaUrl($imageSrc, ['_secure' => $block->getRequest()->isSecure()]);
?>

<form action="<?= /* @noEscape */ $block->getUrl('mplabels/label/labelsave', ['_secure' =>
    $block->getRequest()->isSecure()])?>" enctype="multipart/form-data" 
    method="post" id="edit-product" data-form="edit-product" 
    data-mage-init='{"validation":{}}'>
<input id="seller_id" name="seller_id" type="hidden" value=<?= /* @noEscape */ $block->getSellerId()?>>
<input id="id" name="id" type="hidden" value=<?= /* @noEscape */ $labeldata[0]['id']?>>
    <div class="wk-mp-design" id="wk-bodymain">
        <fieldset class="fieldset info wk-mp-fieldset">
            <div data-mage-init='{"formButtonAction": {}}' class="wk-mp-page-title legend">
                <span><?= /* @noEscape */ __('Label Information') ?></span>
                <button class="button wk-mp-btn" title="<?= /* @noEscape */ __('Save') ?>" type="submit" id="save-btn">
                    <span><span><?= /* @noEscape */ __('Save') ?></span></span>
                </button>
            </div>

            <div class="field required">
                <label class="label"><?= /* @noEscape */ __('Label Title') ?>:</label>
                <div class="control">
                    <input type="text" class="required-entry input-text" 
                    name="label_name" id="name" 
                    value="<?= /* @noEscape */ $labeldata[0]['label_name']?>"/>
                </div>
            </div>
            <?php
            if ($_helper->getConfigData('label_edit_approval')) { ?>     
                <input name="status" type="hidden" value="3">
                <?php
            }
            if (!$_helper->getConfigData('label_edit_approval') && !$_helper->getConfigData('label_approval')) { ?>
                <div class="field">
                    <label class="label"><?= /* @noEscape */ __('Status') ?>:</label>
                    <div class="control">
                        <select name="status" class="mpproduct-select" id="status">
                            <option value="1"><?= /* @noEscape */ __('Enabled') ?></option>
                            <option value="0" 
                            <?= /* @noEscape */ isset($statusYes)?'selected':'' ?>>
                            <?= /* @noEscape */ __('Disabled') ?></option>
                        </select>
                    </div>
                </div>
                <?php
            } ?>

            <div class="field">
                <label class="label"><?= /* @noEscape */ __('Position') ?>:</label>
                <div class="control">

                <select name="position" class="mpproduct-select" id="position">
                    <?php foreach ($position as $var => $position): ?>
                        <option 
                        value="<?= /* @noEscape */ $var ?>"
                        <?php if ($var == $labeldata[0]['position']): ?>
                        selected="selected"<?php endif; ?>>
                        <?= /* @noEscape */ $position ?></option>
                    <?php endforeach; ?>
                </select>
                   
                </div>
            </div>
            <?php
            if ($_helper->getConfigData('label_dimension_manage')) { ?> 
                <div class="field required">
                    <label class="label"><?= /* @noEscape */ __('Label Width For Product Page') ?>:</label>
                    <div class="control">
                        <input type="text" 
                        class="required-entry input-text validate-digits validate-digits-range digits-range-1-100" 
                        name="label_width_productpage" 
                        id="label_width_productpage" 
                        value="<?= /* @noEscape */ $labeldata[0]['label_width_productpage']?>"/>
                        <span class="note">
                            <span><?= /* @noEscape */ __('Should be integer value like 30,
                            value calculated in percentage.');?>
                            </span>
                        </span>
                    </div>
                </div>
                <div class="field required">
                    <label class="label"><?= /* @noEscape */ __('Label Height For Product Page') ?>:</label>
                    <div class="control">
                        <input type="text" 
                        class="required-entry input-text validate-digits validate-digits-range digits-range-1-100" 
                        name="label_height_productpage" 
                        id="label_height_productpage" 
                        value="<?= /* @noEscape */ $labeldata[0]['label_height_productpage']?>"/>
                        <span class="note">
                            <span><?= /* @noEscape */ __('Should be integer value like 30,
                            value calculated in percentage.');?>
                            </span>
                        </span>
                    </div>
                </div>
                <div class="field required">
                    <label class="label"><?= /* @noEscape */ __('Label Width For Category Page') ?>:</label>
                    <div class="control">
                        <input type="text" 
                        class="required-entry input-text validate-digits validate-digits-range digits-range-1-100" 
                        name="label_width_categorypage" 
                        id="label_width_categorypage" 
                        value="<?= /* @noEscape */ $labeldata[0]['label_width_categorypage']?>"/>
                        <span class="note">
                            <span>
                                <?= /* @noEscape */ __('Should be integer value like 30,
                                value calculated in percentage.');?>
                            </span>
                        </span>
                    </div>
                </div>
                <div class="field required">
                    <label class="label"><?= /* @noEscape */ __('Label Height For Category Page') ?>:</label>
                    <div class="control">
                        <input type="text" 
                        class="required-entry input-text validate-digits validate-digits-range digits-range-1-100" 
                        name="label_height_categoryage" id="label_height_categoryage" 
                        value="<?= /* @noEscape */ $labeldata[0]['label_height_categoryage']?>"/>
                        <span class="note">
                            <span><?= /* @noEscape */ __('Should be integer value like 30,
                                value calculated in percentage.');?>
                            </span>
                        </span>
                    </div>
                </div>
                <?php
            } ?>
            <div class="field required">
                <label class="label"><?= /* @noEscape */ __('Upload Image') ?>:</label>
                <input type="file" name="image_name" id="image_name" class="input-text custom_file"><br>
                <span class="note"><span><?= /* @noEscape */ __('Allowed Image Extensions are : ');
                echo $allowedImgExtensions; ?></span></span>
            </div>
        </fieldset>
    </div>
</form>
<div class="mplabel_image_display">
    <img src="<?= /* @noEscape */ $imageSrc?>" id="customfields_your_image_image" 
    title="Preview Image" class="prev-label"/>
</div>

<script type="text/x-magento-init">
    {
        "*":{
            "Webkul_MarketplaceProductLabels/js/labelPreview":{                  
            }
        }
    }
</script>