<?php

/** @var \Fifo\CreditTerms\Block\Payment\Form $block */

$creditTermsOptions = $block->getBuyerCreditTerms();
$crNumber = !is_null($block->getCustomer()->getCustomAttribute('cr_number')) ? $block->getCustomer()->getCustomAttribute('cr_number')->getValue() : '';
$company = !is_null($block->getCustomer()->getCustomAttribute('company')) ? $block->getCustomer()->getCustomAttribute('company')->getValue() : '';
$mobileNumber = !is_null($block->getCustomer()->getCustomAttribute('mobile_number')) ? $block->getCustomer()->getCustomAttribute('mobile_number')->getValue() : '';

$appCollection = $block->getCreditApplicationCollection();

?>

<?php if(empty($appCollection)): ?>

<form class="form credit-payment-term-form" action="<?= $block->escapeUrl($block->getSubmitFormAction()) ?>"
      method="post" id="form-validate-payment-creditterm" enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      autocomplete="off">

    <fieldset class="fieldset">
        <div class="field email required" data-container="change-email">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email"
                       autocomplete="email" data-input="change-email"
                       required="required"
                       value="<?= $block->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       class="input-text" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>
        <div class="field commercial-registration-number required">
            <label class="label" for="commercial-registration-number">
                <span><?= $block->escapeHtml(__('Commercial Registration Number')) ?></span>
            </label>
            <div class="control">
                <input type="text" class="input-text"
                       required="required"
                       data-validate="{required:true}"
                       name="cr_number" id="commercial-registration-number"
                       value="<?= $crNumber ?>"
                       autocomplete="off" />
            </div>
        </div>
        <div class="field company-name required">
            <label class="label" for="company-name">
                <span><?= $block->escapeHtml(__('Company Name')) ?></span>
            </label>
            <div class="control">
                <input type="text" class="input-text"
                       required="required"
                       data-validate="{required:true}"
                       name="company_name" id="company-name"
                       value="<?= $company ?>"
                       autocomplete="off" />
            </div>
        </div>
        <div class="field restaurant-name required">
            <label class="label" for="restaurant-name">
                <span><?= $block->escapeHtml(__('Restaurant Name')) ?></span>
            </label>
            <div class="control">
                <input type="text" class="input-text"
                       required="required"
                       data-validate="{required:true}"
                       name="restaurant_name" id="restaurant-name"
                       autocomplete="off" />
            </div>
        </div>
        <div class="field number-of-branches required">
            <label class="label" for="number-of-branches">
                <span><?= $block->escapeHtml(__('Number of Branches')) ?></span>
            </label>
            <div class="control">
                <input type="text" class="input-text"
                       required="required"
                       data-validate="{required:true}"
                       name="number_of_branches" id="number-of-branches"
                       autocomplete="off" />
            </div>
        </div>
        <div class="field country required">
            <label class="label" for="country">
                <span><?= $block->escapeHtml(__('Country')) ?></span>
            </label>
            <div class="control">
                <select name="location" id="country" class="input-select" required="required" data-validate="{required:true}">
                    <?php foreach ($block->getCountryList() as $countryCode => $countryData): ?>
                        <option value="<?php echo $countryData ?>">
                            <?php echo $countryData;  ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

        <div class="field region required">
            <label class="label" for="state"><span><?php /* @escapeNotVerified */ echo __('Region') ?></span></label>
            <div class="control">
                <input name="region" id="state" class="required-entry input-text" type="text"/>
            </div>
        </div>

        <div class="field owner-name required">
            <label class="label" for="owner-name">
                <span><?= $block->escapeHtml(__('Owner Name')) ?></span>
            </label>
            <div class="control">
                <input type="text" class="input-text"
                       required="required"
                       data-validate="{required:true}"
                       name="owner_name" id="owner-name"
                       value="<?= $block->escapeHtmlAttr($block->getCustomer()->getFirstname()) ?> <?= $block->escapeHtmlAttr($block->getCustomer()->getLastname()) ?>"
                       autocomplete="off" />
            </div>
        </div>
        <div class="field contact-person-name required">
            <label class="label" for="contact-person-name">
                <span><?= $block->escapeHtml(__('Contact person Name')) ?></span>
            </label>
            <div class="control">
                <input type="text" class="input-text"
                       required="required"
                       data-validate="{required:true}"
                       name="contact_person_name" id="contact-person-name"
                       autocomplete="off" />
            </div>
        </div>
        <div class="field contact-number required">
            <label class="label" for="contact-number">
                <span><?= $block->escapeHtml(__('Contact Number (Mobile / Phone)')) ?></span>
            </label>
            <div class="control">
                <input type="text" class="input-text"
                       required="required"
                       data-validate="{required:true}"
                       name="contact_number" id="contact-number"
                       value="<?= $mobileNumber ?>"
                       autocomplete="off" />
            </div>
        </div>
        <div class="field contact-email required">
            <label class="label" for="contact-email">
                <span><?= $block->escapeHtml(__('Contact Email')) ?></span>
            </label>
            <div class="control">
                <input type="text" class="input-text"
                       required="required"
                       data-validate="{required:true}"
                       name="contact_email" id="contact-email"
                       autocomplete="off" />
            </div>
        </div>
        <div class="field buyer-credit-term required">
            <label class="label" for="buyer-credit-term">
                <span><?= $block->escapeHtml(__('Buyer Credit Term')) ?></span>
            </label>
            <div class="control">
                <select class="input-select" name="buyer_credit_terms" required="required" data-validate="{required:true}" id="buyer-credit-term">
                    <?php foreach ($creditTermsOptions as $option) {?>
                        <option value="<?= $block->escapeQuote($option['value']); ?>">
                            <?= /**@noEscape */ $option['label'] ?>
                        </option>
                    <?php } ?>
                </select>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
                <span><?= $block->escapeHtml(__('Save')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
<script>
    require(['jquery',"mage/mage"], function(jQuery){
        var dataForm = jQuery('#form-validate-payment-creditterm');
        dataForm.mage('validation', {});
        jQuery(".field.region #state").attr("disabled", "disabled");

        jQuery(document).on('change','#country',function() {
            var param = 'country_id='+jQuery('#country').val();
            console.log(param);
            if(param === ''){
                console.log('empty');
                jQuery(".field.region #state").attr("disabled", "disabled");
            }else{
                jQuery(".field.region #state").removeAttr("disabled");
            }

            jQuery.ajax({
                showLoader: true,
                url: '<?php /* @escapeNotVerified */ echo $block->getRegionsAction(); ?>',
                data: param,
                type: "GET",
                dataType: 'json'
            }).done(function (data) {
                jQuery('#state').replaceWith(data.value);
            });
        });
    });
</script>

<?php else: ?>
    <div> <b>Note:</b> You Application has been Submitted. </div>
    <table style="margin-top: 10px;">
        <tr>
            <th>Date</th>
            <th>Term Category</th>
            <th>Payment Terms</th>
            <th>Credit Limits</th>
            <th>Status</th>
        </tr>
        <tr>
            <td><?php echo $appCollection['date'] ?></td>
            <td><?php echo $appCollection['term_category'] ?></td>
            <td><?php echo $appCollection['term_days'] ?></td>
            <td><?php echo $appCollection['term_limit'] ?></td>
            <td><?php echo $appCollection['status'] ?></td>
        </tr>
    </table>

<?php endif; ?>

