<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Otp
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

/** @var \Fifo\CreditTerms\Block\Payment\Form $block */
?>
<form class="form form-edit-account" action="<?= $block->escapeUrl($block->getUrl('customer/account/editPost')) ?>"
      method="post" id="form-validate" enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      autocomplete="off">

    <fieldset class="fieldset">
        <div class="field email required" data-container="change-email">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email"
                       autocomplete="email" data-input="change-email"
                       value="<?= $block->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       class="input-text" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>
        <div class="field commercial-registration-number required">
            <label class="label" for="commercial-registration-number">
                <span><?= $block->escapeHtml(__('Commercial Registration Number')) ?></span>
            </label>
            <div class="control">
                <input type="text" class="input-text"
                       name="commercial_registration_number" id="commercial-registration-number"
                       autocomplete="off" />
            </div>
        </div>
        <div class="field company-name required">
            <label class="label" for="company-name">
                <span><?= $block->escapeHtml(__('Company Name')) ?></span>
            </label>
            <div class="control">
                <input type="text" class="input-text"
                       name="company_name" id="company-name"
                       autocomplete="off" />
            </div>
        </div>
        <div class="field restaurant-name required">
            <label class="label" for="restaurant-name">
                <span><?= $block->escapeHtml(__('Restaurant Name')) ?></span>
            </label>
            <div class="control">
                <input type="text" class="input-text"
                       name="restaurant_name" id="restaurant-name"
                       autocomplete="off" />
            </div>
        </div>
        <div class="field number-of-branches required">
            <label class="label" for="number-of-branches">
                <span><?= $block->escapeHtml(__('Number of Branches')) ?></span>
            </label>
            <div class="control">
                <input type="text" class="input-text"
                       name="number_of_branches" id="number-of-branches"
                       autocomplete="off" />
            </div>
        </div>
        <div class="field location-region required">
            <label class="label" for="location-region">
                <span><?= $block->escapeHtml(__('Location / Region')) ?></span>
            </label>
            <div class="control">
                <input type="text" class="input-text"
                       name="location_region" id="location-region"
                       autocomplete="off" />
            </div>
        </div>
        <div class="field owner-name required">
            <label class="label" for="owner-name">
                <span><?= $block->escapeHtml(__('Owner Name')) ?></span>
            </label>
            <div class="control">
                <input type="text" class="input-text"
                       name="owner_name" id="owner-name"
                       autocomplete="off" />
            </div>
        </div>
        <div class="field contact-person-name required">
            <label class="label" for="contact-person-name">
                <span><?= $block->escapeHtml(__('Contact person Name')) ?></span>
            </label>
            <div class="control">
                <input type="text" class="input-text"
                       name="contact_person_name" id="contact-person-name"
                       autocomplete="off" />
            </div>
        </div>
        <div class="field contact-number required">
            <label class="label" for="contact-number">
                <span><?= $block->escapeHtml(__('Contact Number (Mobile / Phone)')) ?></span>
            </label>
            <div class="control">
                <input type="text" class="input-text"
                       name="contact_number" id="contact-number"
                       autocomplete="off" />
            </div>
        </div>
        <div class="field contact-email required">
            <label class="label" for="contact-email">
                <span><?= $block->escapeHtml(__('Contact Email')) ?></span>
            </label>
            <div class="control">
                <input type="text" class="input-text"
                       name="contact_email" id="contact-email"
                       autocomplete="off" />
            </div>
        </div>
        <div class="field buyer-credit-term required">
            <label class="label" for="buyer-credit-term">
                <span><?= $block->escapeHtml(__('Buyer Credit Term')) ?></span>
            </label>
            <div class="control">
                <input type="text" class="input-text"
                       name="buyer_credit_term" id="buyer-credit-term"
                       autocomplete="off" />
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
                <span><?= $block->escapeHtml(__('Save')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
